export type UseGroup = "Militar" | "Comercial" | "Privada / General" | "Histórica" | "Carga" | "Entrenamiento" | "Experimental";

export type Aircraft = {
  slug: string;
  name: string;
  manufacturer: string;
  country: string;
  use: UseGroup;
  category: string;
  era: string;
  status: string;
  firstFlight: string;
  maxSpeed: string;
  range: string;
  ceiling: string;
  engines: string;
  crew: string;
  capacity: string;
  license: string;
  summary: string;
  wikiTitle: string;
};

export const aircraft: Aircraft[] = [
  {
    slug: "f-22-raptor",
    name: "F-22 Raptor",
    manufacturer: "Lockheed Martin / Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Caza furtivo de superioridad aérea",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1997",
    maxSpeed: "Mach 2.25 aprox.",
    range: "2.960 km aprox.",
    ceiling: "19.800 m aprox.",
    engines: "2 × Pratt & Whitney F119",
    crew: "1",
    capacity: "Armamento aire-aire / aire-tierra interno",
    license: "Piloto militar avanzado",
    summary: "Caza furtivo de quinta generación diseñado para superioridad aérea, alta maniobrabilidad y baja observabilidad.",
    wikiTitle: "Lockheed_Martin_F-22_Raptor"
  },
  {
    slug: "f-35-lightning-ii",
    name: "F-35 Lightning II",
    manufacturer: "Lockheed Martin",
    country: "Estados Unidos",
    use: "Militar",
    category: "Caza multirrol furtivo",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2006",
    maxSpeed: "Mach 1.6 aprox.",
    range: "2.200 km aprox.",
    ceiling: "15.000 m aprox.",
    engines: "1 × Pratt & Whitney F135",
    crew: "1",
    capacity: "Armamento interno y externo según misión",
    license: "Piloto militar avanzado",
    summary: "Caza furtivo multirrol con sensores integrados, variantes CTOL, STOVL y embarcada.",
    wikiTitle: "Lockheed_Martin_F-35_Lightning_II"
  },
  {
    slug: "f-16-fighting-falcon",
    name: "F-16 Fighting Falcon",
    manufacturer: "General Dynamics / Lockheed Martin",
    country: "Estados Unidos",
    use: "Militar",
    category: "Caza multirrol",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1974",
    maxSpeed: "Mach 2 aprox.",
    range: "4.200 km ferry aprox.",
    ceiling: "15.000 m+ aprox.",
    engines: "1 × turbofán",
    crew: "1 o 2",
    capacity: "Armamento aire-aire y aire-tierra",
    license: "Piloto militar avanzado",
    summary: "Uno de los cazas multirrol más difundidos del mundo por costo, versatilidad y modernizaciones.",
    wikiTitle: "General_Dynamics_F-16_Fighting_Falcon"
  },
  {
    slug: "f-15-eagle",
    name: "F-15 Eagle",
    manufacturer: "McDonnell Douglas / Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Caza de superioridad aérea",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1972",
    maxSpeed: "Mach 2.5 aprox.",
    range: "5.500 km ferry aprox.",
    ceiling: "20.000 m aprox.",
    engines: "2 × turbofán",
    crew: "1 o 2",
    capacity: "Misiles y bombas según variante",
    license: "Piloto militar avanzado",
    summary: "Caza pesado de superioridad aérea, base de variantes de ataque como el F-15E Strike Eagle.",
    wikiTitle: "McDonnell_Douglas_F-15_Eagle"
  },
  {
    slug: "f-a-18-super-hornet",
    name: "F/A-18E/F Super Hornet",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Caza naval multirrol",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1995",
    maxSpeed: "Mach 1.6 aprox.",
    range: "2.300 km ferry aprox.",
    ceiling: "15.000 m aprox.",
    engines: "2 × General Electric F414",
    crew: "1 o 2",
    capacity: "Armamento naval y terrestre",
    license: "Piloto militar naval avanzado",
    summary: "Caza embarcado utilizado desde portaaviones para defensa aérea, ataque y apoyo naval.",
    wikiTitle: "Boeing_F/A-18E/F_Super_Hornet"
  },
  {
    slug: "eurofighter-typhoon",
    name: "Eurofighter Typhoon",
    manufacturer: "Eurofighter GmbH",
    country: "Consorcio europeo",
    use: "Militar",
    category: "Caza multirrol",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1994",
    maxSpeed: "Mach 2 aprox.",
    range: "2.900 km ferry aprox.",
    ceiling: "16.700 m aprox.",
    engines: "2 × Eurojet EJ200",
    crew: "1 o 2",
    capacity: "Armamento aire-aire y aire-tierra",
    license: "Piloto militar avanzado",
    summary: "Caza europeo de alta maniobrabilidad con enfoque en defensa aérea y capacidades multirrol.",
    wikiTitle: "Eurofighter_Typhoon"
  },
  {
    slug: "dassault-rafale",
    name: "Dassault Rafale",
    manufacturer: "Dassault Aviation",
    country: "Francia",
    use: "Militar",
    category: "Caza multirrol",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1986",
    maxSpeed: "Mach 1.8 aprox.",
    range: "3.700 km ferry aprox.",
    ceiling: "15.000 m aprox.",
    engines: "2 × Snecma M88",
    crew: "1 o 2",
    capacity: "Misiles, bombas y cargas externas",
    license: "Piloto militar avanzado",
    summary: "Caza francés multirrol con versiones terrestres y navales, usado para defensa aérea y ataque.",
    wikiTitle: "Dassault_Rafale"
  },
  {
    slug: "saab-jas-39-gripen",
    name: "Saab JAS 39 Gripen",
    manufacturer: "Saab",
    country: "Suecia",
    use: "Militar",
    category: "Caza ligero multirrol",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1988",
    maxSpeed: "Mach 2 aprox.",
    range: "3.200 km ferry aprox.",
    ceiling: "15.000 m aprox.",
    engines: "1 × turbofán",
    crew: "1 o 2",
    capacity: "Armamento multirrol",
    license: "Piloto militar avanzado",
    summary: "Caza ligero sueco diseñado para operar con logística austera y alta disponibilidad.",
    wikiTitle: "Saab_JAS_39_Gripen"
  },
  {
    slug: "mig-29",
    name: "MiG-29 Fulcrum",
    manufacturer: "Mikoyan",
    country: "Unión Soviética / Rusia",
    use: "Militar",
    category: "Caza",
    era: "Guerra Fría / Moderna",
    status: "Activo en varios países",
    firstFlight: "1977",
    maxSpeed: "Mach 2.25 aprox.",
    range: "2.100 km ferry aprox.",
    ceiling: "18.000 m aprox.",
    engines: "2 × Klimov RD-33",
    crew: "1 o 2",
    capacity: "Misiles aire-aire y cargas externas",
    license: "Piloto militar avanzado",
    summary: "Caza soviético de gran maniobrabilidad, ampliamente exportado y modernizado.",
    wikiTitle: "Mikoyan_MiG-29"
  },
  {
    slug: "su-27",
    name: "Sukhoi Su-27",
    manufacturer: "Sukhoi",
    country: "Unión Soviética / Rusia",
    use: "Militar",
    category: "Caza de superioridad aérea",
    era: "Guerra Fría / Moderna",
    status: "Activo en variantes",
    firstFlight: "1977",
    maxSpeed: "Mach 2.35 aprox.",
    range: "3.500 km aprox.",
    ceiling: "19.000 m aprox.",
    engines: "2 × Saturn AL-31",
    crew: "1",
    capacity: "Armamento aire-aire y aire-tierra",
    license: "Piloto militar avanzado",
    summary: "Caza pesado soviético que dio origen a una familia de variantes modernas como Su-30 y Su-35.",
    wikiTitle: "Sukhoi_Su-27"
  },
  {
    slug: "su-57",
    name: "Sukhoi Su-57",
    manufacturer: "Sukhoi",
    country: "Rusia",
    use: "Militar",
    category: "Caza furtivo multirrol",
    era: "Moderna",
    status: "Activo / producción limitada",
    firstFlight: "2010",
    maxSpeed: "Mach 2 aprox.",
    range: "3.500 km aprox.",
    ceiling: "20.000 m aprox.",
    engines: "2 × turbofán",
    crew: "1",
    capacity: "Armamento interno y externo",
    license: "Piloto militar avanzado",
    summary: "Caza ruso de quinta generación con enfoque en baja observabilidad, supermaniobrabilidad y sensores.",
    wikiTitle: "Sukhoi_Su-57"
  },
  {
    slug: "chengdu-j-20",
    name: "Chengdu J-20",
    manufacturer: "Chengdu Aerospace Corporation",
    country: "China",
    use: "Militar",
    category: "Caza furtivo",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2011",
    maxSpeed: "Mach 2 aprox.",
    range: "Estimado superior a 2.000 km",
    ceiling: "Estimado 18.000 m+",
    engines: "2 × turbofán",
    crew: "1",
    capacity: "Armamento interno y externo",
    license: "Piloto militar avanzado",
    summary: "Caza furtivo chino de largo alcance orientado a superioridad aérea y operaciones avanzadas.",
    wikiTitle: "Chengdu_J-20"
  },
  {
    slug: "b-2-spirit",
    name: "B-2 Spirit",
    manufacturer: "Northrop Grumman",
    country: "Estados Unidos",
    use: "Militar",
    category: "Bombardero furtivo estratégico",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1989",
    maxSpeed: "1.010 km/h aprox.",
    range: "11.000 km aprox.",
    ceiling: "15.000 m aprox.",
    engines: "4 × turbofán",
    crew: "2",
    capacity: "Carga bélica estratégica",
    license: "Piloto militar estratégico",
    summary: "Bombardero furtivo de ala volante diseñado para penetración de largo alcance.",
    wikiTitle: "Northrop_B-2_Spirit"
  },
  {
    slug: "b-52-stratofortress",
    name: "B-52 Stratofortress",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Bombardero estratégico",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1952",
    maxSpeed: "1.000 km/h aprox.",
    range: "14.000 km+ aprox.",
    ceiling: "15.000 m aprox.",
    engines: "8 × turbofán",
    crew: "5",
    capacity: "Carga bélica convencional o estratégica",
    license: "Piloto militar estratégico",
    summary: "Bombardero estratégico de muy larga vida operativa y alta capacidad de carga.",
    wikiTitle: "Boeing_B-52_Stratofortress"
  },
  {
    slug: "tu-160",
    name: "Tupolev Tu-160",
    manufacturer: "Tupolev",
    country: "Rusia",
    use: "Militar",
    category: "Bombardero supersónico estratégico",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1981",
    maxSpeed: "Mach 2 aprox.",
    range: "12.000 km aprox.",
    ceiling: "16.000 m aprox.",
    engines: "4 × turbofán",
    crew: "4",
    capacity: "Misiles y carga estratégica",
    license: "Piloto militar estratégico",
    summary: "Bombardero supersónico de ala de geometría variable, conocido por su tamaño y alcance.",
    wikiTitle: "Tupolev_Tu-160"
  },
  {
    slug: "a-10-thunderbolt-ii",
    name: "A-10 Thunderbolt II",
    manufacturer: "Fairchild Republic",
    country: "Estados Unidos",
    use: "Militar",
    category: "Ataque cercano",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1972",
    maxSpeed: "706 km/h aprox.",
    range: "4.100 km ferry aprox.",
    ceiling: "13.700 m aprox.",
    engines: "2 × turbofán",
    crew: "1",
    capacity: "Cañón GAU-8 y armamento externo",
    license: "Piloto militar de ataque",
    summary: "Avión de ataque cercano diseñado para apoyo a tropas terrestres y supervivencia en combate.",
    wikiTitle: "Fairchild_Republic_A-10_Thunderbolt_II"
  },
  {
    slug: "c-130-hercules",
    name: "C-130 Hercules",
    manufacturer: "Lockheed Martin",
    country: "Estados Unidos",
    use: "Militar",
    category: "Transporte militar táctico",
    era: "Guerra Fría / Moderna",
    status: "Activo",
    firstFlight: "1954",
    maxSpeed: "590 km/h aprox.",
    range: "3.800 km aprox.",
    ceiling: "10.000 m aprox.",
    engines: "4 × turbohélice",
    crew: "3 a 5",
    capacity: "Tropas, carga o evacuación médica",
    license: "Piloto militar de transporte",
    summary: "Transporte táctico robusto usado por numerosas fuerzas aéreas para carga, tropas y misiones especiales.",
    wikiTitle: "Lockheed_C-130_Hercules"
  },
  {
    slug: "c-17-globemaster-iii",
    name: "C-17 Globemaster III",
    manufacturer: "McDonnell Douglas / Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Transporte militar estratégico",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1991",
    maxSpeed: "830 km/h aprox.",
    range: "4.480 km con carga aprox.",
    ceiling: "13.700 m aprox.",
    engines: "4 × turbofán",
    crew: "3",
    capacity: "Carga pesada, vehículos o tropas",
    license: "Piloto militar de transporte pesado",
    summary: "Transporte estratégico capaz de operar en pistas relativamente cortas y llevar carga pesada.",
    wikiTitle: "McDonnell_Douglas_C-17_Globemaster_III"
  },
  {
    slug: "p-8-poseidon",
    name: "P-8 Poseidon",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Patrulla marítima",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2009",
    maxSpeed: "907 km/h aprox.",
    range: "8.300 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "Variable según misión",
    capacity: "Sensores, sonoboyas y armamento antisubmarino",
    license: "Piloto militar multimotor",
    summary: "Avión de patrulla marítima y guerra antisubmarina derivado del Boeing 737.",
    wikiTitle: "Boeing_P-8_Poseidon"
  },
  {
    slug: "e-3-sentry",
    name: "E-3 Sentry",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Militar",
    category: "Alerta temprana y control aéreo",
    era: "Guerra Fría / Moderna",
    status: "Activo en varias fuerzas",
    firstFlight: "1972",
    maxSpeed: "855 km/h aprox.",
    range: "7.400 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "4 × turbofán",
    crew: "Tripulación de vuelo y misión",
    capacity: "Radar AWACS y consolas de control",
    license: "Piloto militar multimotor",
    summary: "Plataforma AWACS para vigilancia aérea, mando y control de operaciones.",
    wikiTitle: "Boeing_E-3_Sentry"
  },

  {
    slug: "airbus-a320",
    name: "Airbus A320",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Narrow-body",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1987",
    maxSpeed: "Mach 0.82 aprox.",
    range: "6.100 km aprox.",
    ceiling: "12.100 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "Hasta 180 pasajeros aprox.",
    license: "ATPL + Type Rating A320",
    summary: "Familia comercial de pasillo único, muy usada en rutas cortas y medias.",
    wikiTitle: "Airbus_A320_family"
  },
  {
    slug: "airbus-a321neo",
    name: "Airbus A321neo",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Narrow-body de largo alcance",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2016",
    maxSpeed: "Mach 0.82 aprox.",
    range: "7.400 km aprox. en variantes LR/XLR",
    ceiling: "12.100 m aprox.",
    engines: "2 × turbofán eficientes",
    crew: "2 pilotos",
    capacity: "Hasta 240 pasajeros aprox.",
    license: "ATPL + Type Rating A320 family",
    summary: "Versión alargada y eficiente del A320neo, usada para rutas de alta demanda y alcance extendido.",
    wikiTitle: "Airbus_A321neo"
  },
  {
    slug: "airbus-a330",
    name: "Airbus A330",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Wide-body",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1992",
    maxSpeed: "Mach 0.86 aprox.",
    range: "13.400 km aprox. según variante",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "250 a 300+ pasajeros aprox.",
    license: "ATPL + Type Rating A330",
    summary: "Avión comercial de fuselaje ancho para rutas medias y largas, con variantes de pasajeros, carga y cisterna.",
    wikiTitle: "Airbus_A330"
  },
  {
    slug: "airbus-a340",
    name: "Airbus A340",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Wide-body cuatrimotor",
    era: "Moderna",
    status: "Retirado o reducido en muchas aerolíneas",
    firstFlight: "1991",
    maxSpeed: "Mach 0.86 aprox.",
    range: "13.700 km+ aprox.",
    ceiling: "12.500 m aprox.",
    engines: "4 × turbofán",
    crew: "2 pilotos",
    capacity: "250 a 370 pasajeros aprox.",
    license: "ATPL + Type Rating A340",
    summary: "Cuatrimotor de largo alcance, importante antes del dominio de los bimotores ETOPS.",
    wikiTitle: "Airbus_A340"
  },
  {
    slug: "airbus-a350",
    name: "Airbus A350",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Wide-body moderno",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2013",
    maxSpeed: "Mach 0.89 aprox.",
    range: "15.000 km+ aprox.",
    ceiling: "13.100 m aprox.",
    engines: "2 × Rolls-Royce Trent XWB",
    crew: "2 pilotos",
    capacity: "300 a 410 pasajeros aprox.",
    license: "ATPL + Type Rating A350",
    summary: "Avión de largo alcance con uso intensivo de materiales compuestos y alta eficiencia.",
    wikiTitle: "Airbus_A350"
  },
  {
    slug: "airbus-a380",
    name: "Airbus A380",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Comercial",
    category: "Superjumbo wide-body",
    era: "Moderna",
    status: "Activo en operadores seleccionados",
    firstFlight: "2005",
    maxSpeed: "Mach 0.89 aprox.",
    range: "15.200 km aprox.",
    ceiling: "13.100 m aprox.",
    engines: "4 × turbofán",
    crew: "2 pilotos",
    capacity: "Hasta 853 pasajeros en configuración alta densidad",
    license: "ATPL + Type Rating A380",
    summary: "El avión de pasajeros más grande del mundo, diseñado para rutas de alta densidad entre grandes hubs.",
    wikiTitle: "Airbus_A380"
  },
  {
    slug: "boeing-737",
    name: "Boeing 737",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Narrow-body",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1967",
    maxSpeed: "Mach 0.82 aprox.",
    range: "5.000 a 6.500 km aprox. según variante",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "130 a 230 pasajeros aprox.",
    license: "ATPL + Type Rating 737",
    summary: "Familia de pasillo único muy extendida en rutas cortas y medias alrededor del mundo.",
    wikiTitle: "Boeing_737"
  },
  {
    slug: "boeing-747",
    name: "Boeing 747",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Wide-body / Jumbo",
    era: "Clásica / Moderna",
    status: "Pasajeros reducido; carga activo",
    firstFlight: "1969",
    maxSpeed: "Mach 0.85 aprox.",
    range: "13.450 km aprox.",
    ceiling: "13.700 m aprox.",
    engines: "4 × turbofán",
    crew: "2 pilotos en variantes modernas",
    capacity: "Pasajeros o carga pesada",
    license: "ATPL + Type Rating 747",
    summary: "Icónico jumbo de largo alcance que cambió la aviación comercial y sigue siendo clave en carga.",
    wikiTitle: "Boeing_747"
  },
  {
    slug: "boeing-757",
    name: "Boeing 757",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Narrow-body mediano",
    era: "Moderna",
    status: "Activo en pasajeros y carga",
    firstFlight: "1982",
    maxSpeed: "Mach 0.86 aprox.",
    range: "7.200 km aprox.",
    ceiling: "12.800 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "200 a 240 pasajeros aprox.",
    license: "ATPL + Type Rating 757/767",
    summary: "Avión de pasillo único con gran rendimiento, usado en rutas transcontinentales y cargueras.",
    wikiTitle: "Boeing_757"
  },
  {
    slug: "boeing-767",
    name: "Boeing 767",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Wide-body medio",
    era: "Moderna",
    status: "Activo en pasajeros, carga y militar",
    firstFlight: "1981",
    maxSpeed: "Mach 0.86 aprox.",
    range: "11.000 km aprox.",
    ceiling: "13.100 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "180 a 300 pasajeros aprox.",
    license: "ATPL + Type Rating 757/767",
    summary: "Fuselaje ancho de tamaño medio, muy utilizado en rutas de largo alcance y conversión carguera.",
    wikiTitle: "Boeing_767"
  },
  {
    slug: "boeing-777",
    name: "Boeing 777",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Wide-body largo alcance",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1994",
    maxSpeed: "Mach 0.84 aprox.",
    range: "15.800 km+ aprox. según variante",
    ceiling: "13.100 m aprox.",
    engines: "2 × turbofán de gran empuje",
    crew: "2 pilotos",
    capacity: "300 a 400+ pasajeros aprox.",
    license: "ATPL + Type Rating 777",
    summary: "Bimotor de fuselaje ancho de gran alcance, muy usado en rutas internacionales.",
    wikiTitle: "Boeing_777"
  },
  {
    slug: "boeing-787-dreamliner",
    name: "Boeing 787 Dreamliner",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Comercial",
    category: "Wide-body moderno",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2009",
    maxSpeed: "Mach 0.85 aprox.",
    range: "13.500 km+ aprox.",
    ceiling: "13.100 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "240 a 330 pasajeros aprox.",
    license: "ATPL + Type Rating 787",
    summary: "Avión comercial eficiente de materiales compuestos, pensado para rutas punto a punto de largo alcance.",
    wikiTitle: "Boeing_787_Dreamliner"
  },
  {
    slug: "embraer-e190",
    name: "Embraer E190",
    manufacturer: "Embraer",
    country: "Brasil",
    use: "Comercial",
    category: "Regional jet",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2004",
    maxSpeed: "Mach 0.82 aprox.",
    range: "4.500 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "90 a 114 pasajeros aprox.",
    license: "ATPL + Type Rating E-Jet",
    summary: "Jet regional brasileño usado por aerolíneas para rutas de menor densidad.",
    wikiTitle: "Embraer_E-Jet_family"
  },
  {
    slug: "embraer-e195-e2",
    name: "Embraer E195-E2",
    manufacturer: "Embraer",
    country: "Brasil",
    use: "Comercial",
    category: "Regional jet moderno",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2017",
    maxSpeed: "Mach 0.82 aprox.",
    range: "4.800 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "2 × Pratt & Whitney geared turbofan",
    crew: "2 pilotos",
    capacity: "120 a 146 pasajeros aprox.",
    license: "ATPL + Type Rating E2",
    summary: "Versión moderna de la familia E-Jet con mayor eficiencia y capacidad.",
    wikiTitle: "Embraer_E-Jet_E2_family"
  },
  {
    slug: "atr-72",
    name: "ATR 72",
    manufacturer: "ATR",
    country: "Francia / Italia",
    use: "Comercial",
    category: "Turbohélice regional",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1988",
    maxSpeed: "510 km/h aprox.",
    range: "1.500 km aprox.",
    ceiling: "7.600 m aprox.",
    engines: "2 × turbohélice",
    crew: "2 pilotos",
    capacity: "70 a 78 pasajeros aprox.",
    license: "ATPL/CPL + habilitación de tipo",
    summary: "Turbohélice regional eficiente para rutas cortas, aeropuertos secundarios y costos reducidos.",
    wikiTitle: "ATR_72"
  },
  {
    slug: "bombardier-crj900",
    name: "Bombardier CRJ900",
    manufacturer: "Bombardier",
    country: "Canadá",
    use: "Comercial",
    category: "Regional jet",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2001",
    maxSpeed: "Mach 0.83 aprox.",
    range: "2.900 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "76 a 90 pasajeros aprox.",
    license: "ATPL + Type Rating CRJ",
    summary: "Jet regional de la familia CRJ usado en rutas alimentadoras y de media distancia.",
    wikiTitle: "Bombardier_CRJ900"
  },
  {
    slug: "concorde",
    name: "Concorde",
    manufacturer: "Aérospatiale / BAC",
    country: "Francia / Reino Unido",
    use: "Comercial",
    category: "Supersónico de pasajeros",
    era: "Histórica moderna",
    status: "Retirado",
    firstFlight: "1969",
    maxSpeed: "Mach 2.04 aprox.",
    range: "7.250 km aprox.",
    ceiling: "18.300 m aprox.",
    engines: "4 × Rolls-Royce/Snecma Olympus",
    crew: "3",
    capacity: "92 a 128 pasajeros aprox.",
    license: "ATPL + Type Rating Concorde",
    summary: "Avión supersónico de pasajeros, símbolo de velocidad y lujo en la aviación comercial.",
    wikiTitle: "Concorde"
  },

  {
    slug: "cessna-172",
    name: "Cessna 172 Skyhawk",
    manufacturer: "Cessna",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor de entrenamiento",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1955",
    maxSpeed: "302 km/h aprox.",
    range: "1.185 km aprox.",
    ceiling: "4.100 m aprox.",
    engines: "1 × motor Lycoming",
    crew: "1 piloto",
    capacity: "4 personas",
    license: "PPL",
    summary: "Uno de los aviones de entrenamiento y aviación general más populares de la historia.",
    wikiTitle: "Cessna_172"
  },
  {
    slug: "cessna-182",
    name: "Cessna 182 Skylane",
    manufacturer: "Cessna",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor utilitario",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1956",
    maxSpeed: "278 km/h aprox.",
    range: "1.700 km aprox.",
    ceiling: "5.500 m aprox.",
    engines: "1 × motor pistón",
    crew: "1 piloto",
    capacity: "4 personas",
    license: "PPL",
    summary: "Monomotor robusto de aviación general, utilizado para viajes, entrenamiento y operaciones utilitarias.",
    wikiTitle: "Cessna_182_Skylane"
  },
  {
    slug: "piper-pa-28-cherokee",
    name: "Piper PA-28 Cherokee",
    manufacturer: "Piper Aircraft",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor ligero",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1960",
    maxSpeed: "230 a 280 km/h aprox.",
    range: "800 a 1.300 km aprox.",
    ceiling: "4.000 m aprox.",
    engines: "1 × motor pistón",
    crew: "1 piloto",
    capacity: "4 personas",
    license: "PPL",
    summary: "Familia de aviones ligeros muy usada en entrenamiento, aviación privada y clubes de vuelo.",
    wikiTitle: "Piper_PA-28_Cherokee"
  },
  {
    slug: "piper-pa-46-malibu",
    name: "Piper PA-46 Malibu / Meridian",
    manufacturer: "Piper Aircraft",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor presurizado / turbohélice",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1979",
    maxSpeed: "400 a 480 km/h aprox.",
    range: "2.400 km aprox.",
    ceiling: "7.600 a 9.100 m aprox.",
    engines: "1 × pistón o turbohélice según versión",
    crew: "1 piloto",
    capacity: "5 a 6 personas",
    license: "PPL/CPL + habilitaciones según versión",
    summary: "Avión privado de alto rendimiento, con versiones presurizadas y turbohélice.",
    wikiTitle: "Piper_PA-46"
  },
  {
    slug: "beechcraft-bonanza",
    name: "Beechcraft Bonanza",
    manufacturer: "Beechcraft",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor privado",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1945",
    maxSpeed: "320 km/h aprox.",
    range: "1.700 km aprox.",
    ceiling: "5.600 m aprox.",
    engines: "1 × motor pistón",
    crew: "1 piloto",
    capacity: "4 a 6 personas",
    license: "PPL",
    summary: "Avión privado de alto rendimiento y larga producción, reconocido por su diseño y calidad.",
    wikiTitle: "Beechcraft_Bonanza"
  },
  {
    slug: "beechcraft-king-air",
    name: "Beechcraft King Air",
    manufacturer: "Beechcraft",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Turbohélice ejecutivo",
    era: "Clásica / Moderna",
    status: "Activo",
    firstFlight: "1963",
    maxSpeed: "500 a 570 km/h aprox.",
    range: "2.400 a 3.300 km aprox.",
    ceiling: "10.000 m aprox.",
    engines: "2 × turbohélice",
    crew: "1 o 2 pilotos",
    capacity: "6 a 13 pasajeros aprox.",
    license: "CPL/ATPL + multimotor/turbohélice",
    summary: "Turbohélice ejecutivo y utilitario muy usado por empresas, gobiernos y servicios médicos.",
    wikiTitle: "Beechcraft_King_Air"
  },
  {
    slug: "pilatus-pc-12",
    name: "Pilatus PC-12",
    manufacturer: "Pilatus Aircraft",
    country: "Suiza",
    use: "Privada / General",
    category: "Turbohélice monomotor utilitario",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1991",
    maxSpeed: "528 km/h aprox.",
    range: "3.400 km aprox.",
    ceiling: "9.100 m aprox.",
    engines: "1 × Pratt & Whitney Canada PT6",
    crew: "1 o 2 pilotos",
    capacity: "Hasta 9 pasajeros aprox.",
    license: "CPL/ATPL + habilitación correspondiente",
    summary: "Turbohélice monomotor versátil, usado para transporte ejecutivo, carga ligera, ambulancia y pistas cortas.",
    wikiTitle: "Pilatus_PC-12"
  },
  {
    slug: "cirrus-sr22",
    name: "Cirrus SR22",
    manufacturer: "Cirrus Aircraft",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Monomotor moderno",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2000",
    maxSpeed: "340 km/h aprox.",
    range: "1.900 km aprox.",
    ceiling: "5.300 m aprox.",
    engines: "1 × motor Continental",
    crew: "1 piloto",
    capacity: "4 a 5 personas",
    license: "PPL",
    summary: "Avión ligero moderno con aviónica avanzada y sistema de paracaídas balístico CAPS.",
    wikiTitle: "Cirrus_SR22"
  },
  {
    slug: "diamond-da40",
    name: "Diamond DA40",
    manufacturer: "Diamond Aircraft",
    country: "Austria / Canadá",
    use: "Entrenamiento",
    category: "Entrenador monomotor",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1997",
    maxSpeed: "280 km/h aprox.",
    range: "1.300 km aprox.",
    ceiling: "5.000 m aprox.",
    engines: "1 × motor pistón",
    crew: "1 piloto",
    capacity: "4 personas",
    license: "PPL / entrenamiento inicial",
    summary: "Entrenador moderno de cuatro plazas usado por escuelas de vuelo y pilotos privados.",
    wikiTitle: "Diamond_DA40"
  },
  {
    slug: "diamond-da42",
    name: "Diamond DA42 Twin Star",
    manufacturer: "Diamond Aircraft",
    country: "Austria / Canadá",
    use: "Entrenamiento",
    category: "Entrenador bimotor",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2002",
    maxSpeed: "356 km/h aprox.",
    range: "1.700 km aprox.",
    ceiling: "5.500 m aprox.",
    engines: "2 × motores diésel/aero",
    crew: "1 piloto",
    capacity: "4 personas",
    license: "PPL/CPL + multimotor",
    summary: "Bimotor ligero usado para entrenamiento avanzado, vigilancia y aviación general.",
    wikiTitle: "Diamond_DA42_Twin_Star"
  },
  {
    slug: "gulfstream-g650",
    name: "Gulfstream G650",
    manufacturer: "Gulfstream Aerospace",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Jet ejecutivo ultra largo alcance",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2009",
    maxSpeed: "Mach 0.925 aprox.",
    range: "12.900 km aprox.",
    ceiling: "15.500 m aprox.",
    engines: "2 × Rolls-Royce BR725",
    crew: "2 pilotos",
    capacity: "Hasta 19 pasajeros aprox.",
    license: "ATPL/CPL + Type Rating G650",
    summary: "Jet ejecutivo de ultra largo alcance, alta velocidad y cabina de lujo.",
    wikiTitle: "Gulfstream_G650"
  },
  {
    slug: "bombardier-global-7500",
    name: "Bombardier Global 7500",
    manufacturer: "Bombardier Aviation",
    country: "Canadá",
    use: "Privada / General",
    category: "Jet ejecutivo ultra largo alcance",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2016",
    maxSpeed: "Mach 0.925 aprox.",
    range: "14.260 km aprox.",
    ceiling: "15.500 m aprox.",
    engines: "2 × GE Passport",
    crew: "2 pilotos",
    capacity: "Hasta 19 pasajeros aprox.",
    license: "ATPL/CPL + Type Rating Global",
    summary: "Jet ejecutivo de máximo alcance con cabina grande y prestaciones de largo recorrido.",
    wikiTitle: "Bombardier_Global_7500"
  },
  {
    slug: "cessna-citation-x",
    name: "Cessna Citation X",
    manufacturer: "Cessna",
    country: "Estados Unidos",
    use: "Privada / General",
    category: "Jet ejecutivo rápido",
    era: "Moderna",
    status: "Activo / producción finalizada",
    firstFlight: "1993",
    maxSpeed: "Mach 0.92 aprox.",
    range: "6.400 km aprox.",
    ceiling: "15.500 m aprox.",
    engines: "2 × Rolls-Royce AE 3007",
    crew: "2 pilotos",
    capacity: "8 a 12 pasajeros aprox.",
    license: "ATPL/CPL + Type Rating Citation X",
    summary: "Jet ejecutivo conocido por su alta velocidad de crucero y diseño aerodinámico.",
    wikiTitle: "Cessna_Citation_X"
  },

  {
    slug: "wright-flyer",
    name: "Wright Flyer",
    manufacturer: "Wright Brothers",
    country: "Estados Unidos",
    use: "Histórica",
    category: "Primer avión motorizado controlado",
    era: "Pioneros",
    status: "Histórico",
    firstFlight: "1903",
    maxSpeed: "48 km/h aprox.",
    range: "Muy limitado",
    ceiling: "Baja altitud",
    engines: "1 × motor de pistón temprano",
    crew: "1",
    capacity: "1 piloto",
    license: "No aplicable / histórico",
    summary: "Aeronave asociada al primer vuelo motorizado controlado y sostenido de la historia.",
    wikiTitle: "Wright_Flyer"
  },
  {
    slug: "sopwith-camel",
    name: "Sopwith Camel",
    manufacturer: "Sopwith Aviation Company",
    country: "Reino Unido",
    use: "Histórica",
    category: "Caza de la Primera Guerra Mundial",
    era: "Primera Guerra Mundial",
    status: "Retirado",
    firstFlight: "1916",
    maxSpeed: "185 km/h aprox.",
    range: "485 km aprox.",
    ceiling: "5.800 m aprox.",
    engines: "1 × motor rotativo",
    crew: "1",
    capacity: "2 ametralladoras sincronizadas",
    license: "Histórica / experimental",
    summary: "Caza británico famoso por su maniobrabilidad y dificultad de manejo.",
    wikiTitle: "Sopwith_Camel"
  },
  {
    slug: "fokker-dr-i",
    name: "Fokker Dr.I",
    manufacturer: "Fokker",
    country: "Alemania",
    use: "Histórica",
    category: "Triplano de caza",
    era: "Primera Guerra Mundial",
    status: "Retirado",
    firstFlight: "1917",
    maxSpeed: "185 km/h aprox.",
    range: "300 km aprox.",
    ceiling: "6.000 m aprox.",
    engines: "1 × motor rotativo",
    crew: "1",
    capacity: "2 ametralladoras",
    license: "Histórica / experimental",
    summary: "Triplano alemán asociado a la imagen clásica de la aviación de la Primera Guerra Mundial.",
    wikiTitle: "Fokker_Dr.I"
  },
  {
    slug: "supermarine-spitfire",
    name: "Supermarine Spitfire",
    manufacturer: "Supermarine",
    country: "Reino Unido",
    use: "Histórica",
    category: "Caza de la Segunda Guerra Mundial",
    era: "Segunda Guerra Mundial",
    status: "Retirado / preservado",
    firstFlight: "1936",
    maxSpeed: "594 km/h aprox.",
    range: "760 km aprox.",
    ceiling: "11.300 m aprox.",
    engines: "1 × Rolls-Royce Merlin/Griffon",
    crew: "1",
    capacity: "Armamento de caza",
    license: "Licencia especial / warbird",
    summary: "Caza británico icónico, clave en la Batalla de Inglaterra.",
    wikiTitle: "Supermarine_Spitfire"
  },
  {
    slug: "p-51-mustang",
    name: "P-51 Mustang",
    manufacturer: "North American Aviation",
    country: "Estados Unidos",
    use: "Histórica",
    category: "Caza de escolta",
    era: "Segunda Guerra Mundial",
    status: "Retirado / preservado",
    firstFlight: "1940",
    maxSpeed: "703 km/h aprox.",
    range: "2.600 km aprox.",
    ceiling: "12.800 m aprox.",
    engines: "1 × Packard Merlin",
    crew: "1",
    capacity: "Ametralladoras, bombas o cohetes",
    license: "Licencia especial / warbird",
    summary: "Caza estadounidense de largo alcance, fundamental en escoltas de bombarderos aliados.",
    wikiTitle: "North_American_P-51_Mustang"
  },
  {
    slug: "messerschmitt-bf-109",
    name: "Messerschmitt Bf 109",
    manufacturer: "Messerschmitt",
    country: "Alemania",
    use: "Histórica",
    category: "Caza de la Segunda Guerra Mundial",
    era: "Segunda Guerra Mundial",
    status: "Retirado / preservado",
    firstFlight: "1935",
    maxSpeed: "640 km/h aprox.",
    range: "850 km aprox.",
    ceiling: "12.000 m aprox.",
    engines: "1 × Daimler-Benz",
    crew: "1",
    capacity: "Armamento de caza",
    license: "Licencia especial / warbird",
    summary: "Caza alemán producido en grandes cantidades y usado en numerosos frentes.",
    wikiTitle: "Messerschmitt_Bf_109"
  },
  {
    slug: "zero",
    name: "Mitsubishi A6M Zero",
    manufacturer: "Mitsubishi",
    country: "Japón",
    use: "Histórica",
    category: "Caza naval",
    era: "Segunda Guerra Mundial",
    status: "Retirado / preservado",
    firstFlight: "1939",
    maxSpeed: "533 km/h aprox.",
    range: "3.100 km aprox.",
    ceiling: "10.000 m aprox.",
    engines: "1 × Nakajima Sakae",
    crew: "1",
    capacity: "Cañones, ametralladoras y bombas ligeras",
    license: "Licencia especial / warbird",
    summary: "Caza naval japonés famoso por su alcance y maniobrabilidad al inicio de la guerra del Pacífico.",
    wikiTitle: "Mitsubishi_A6M_Zero"
  },
  {
    slug: "douglas-dc-3",
    name: "Douglas DC-3",
    manufacturer: "Douglas Aircraft Company",
    country: "Estados Unidos",
    use: "Histórica",
    category: "Transporte civil clásico",
    era: "Clásica",
    status: "Histórico / algunos activos",
    firstFlight: "1935",
    maxSpeed: "333 km/h aprox.",
    range: "2.400 km aprox.",
    ceiling: "7.100 m aprox.",
    engines: "2 × motores radiales",
    crew: "2 a 3",
    capacity: "21 a 32 pasajeros aprox.",
    license: "CPL/ATPL histórico según operación",
    summary: "Transporte civil que transformó la aviación comercial y tuvo enorme impacto militar como C-47.",
    wikiTitle: "Douglas_DC-3"
  },
  {
    slug: "lockheed-constellation",
    name: "Lockheed Constellation",
    manufacturer: "Lockheed",
    country: "Estados Unidos",
    use: "Histórica",
    category: "Avión comercial clásico",
    era: "Posguerra",
    status: "Retirado / preservado",
    firstFlight: "1943",
    maxSpeed: "600 km/h aprox.",
    range: "8.700 km aprox.",
    ceiling: "7.600 m aprox.",
    engines: "4 × motores radiales",
    crew: "4+",
    capacity: "60 a 100 pasajeros aprox.",
    license: "ATPL histórico",
    summary: "Elegante cuatrimotor de largo alcance de la era previa al jet comercial.",
    wikiTitle: "Lockheed_Constellation"
  },
  {
    slug: "de-havilland-comet",
    name: "de Havilland Comet",
    manufacturer: "de Havilland",
    country: "Reino Unido",
    use: "Histórica",
    category: "Primer jet comercial",
    era: "Era del jet temprana",
    status: "Retirado",
    firstFlight: "1949",
    maxSpeed: "840 km/h aprox.",
    range: "5.000 km aprox.",
    ceiling: "12.000 m aprox.",
    engines: "4 × turborreactores",
    crew: "4",
    capacity: "36 a 81 pasajeros aprox.",
    license: "ATPL + habilitación histórica",
    summary: "Primer avión comercial a reacción, clave para aprender sobre fatiga estructural y seguridad moderna.",
    wikiTitle: "De_Havilland_Comet"
  },
  {
    slug: "sr-71-blackbird",
    name: "SR-71 Blackbird",
    manufacturer: "Lockheed Skunk Works",
    country: "Estados Unidos",
    use: "Histórica",
    category: "Reconocimiento estratégico supersónico",
    era: "Guerra Fría",
    status: "Retirado",
    firstFlight: "1964",
    maxSpeed: "Mach 3.2+",
    range: "5.400 km aprox.",
    ceiling: "25.900 m aprox.",
    engines: "2 × Pratt & Whitney J58",
    crew: "2",
    capacity: "Sensores de reconocimiento",
    license: "Piloto militar especializado",
    summary: "Avión de reconocimiento de altísima velocidad y altitud, ícono de la ingeniería de la Guerra Fría.",
    wikiTitle: "Lockheed_SR-71_Blackbird"
  },

  {
    slug: "antonov-an-225",
    name: "Antonov An-225 Mriya",
    manufacturer: "Antonov",
    country: "Ucrania / Unión Soviética",
    use: "Carga",
    category: "Carga superpesada",
    era: "Guerra Fría / Moderna",
    status: "Destruido / histórico",
    firstFlight: "1988",
    maxSpeed: "850 km/h aprox.",
    range: "15.400 km ferry aprox.",
    ceiling: "11.000 m aprox.",
    engines: "6 × turbofán",
    crew: "6",
    capacity: "Carga útil extraordinaria hasta 250 t aprox.",
    license: "ATPL + Type Rating especial",
    summary: "El avión más pesado jamás construido, diseñado para transportar cargas excepcionales.",
    wikiTitle: "Antonov_An-225_Mriya"
  },
  {
    slug: "antonov-an-124",
    name: "Antonov An-124 Ruslan",
    manufacturer: "Antonov",
    country: "Ucrania / Unión Soviética",
    use: "Carga",
    category: "Carga pesada estratégica",
    era: "Guerra Fría / Moderna",
    status: "Activo en operadores seleccionados",
    firstFlight: "1982",
    maxSpeed: "865 km/h aprox.",
    range: "5.400 km con carga aprox.",
    ceiling: "12.000 m aprox.",
    engines: "4 × turbofán",
    crew: "6",
    capacity: "Carga pesada sobredimensionada",
    license: "ATPL + Type Rating especial",
    summary: "Uno de los mayores aviones de carga del mundo, usado para transporte sobredimensionado.",
    wikiTitle: "Antonov_An-124_Ruslan"
  },
  {
    slug: "boeing-747-8f",
    name: "Boeing 747-8F",
    manufacturer: "Boeing",
    country: "Estados Unidos",
    use: "Carga",
    category: "Carguero pesado",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2010",
    maxSpeed: "Mach 0.845 aprox.",
    range: "8.100 km con carga aprox.",
    ceiling: "13.100 m aprox.",
    engines: "4 × GEnx",
    crew: "2 pilotos",
    capacity: "Carga aérea intercontinental",
    license: "ATPL + Type Rating 747",
    summary: "Versión carguera moderna del 747, muy utilizada para logística internacional pesada.",
    wikiTitle: "Boeing_747-8"
  },
  {
    slug: "airbus-beluga-xl",
    name: "Airbus BelugaXL",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Carga",
    category: "Carga volumétrica especial",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2018",
    maxSpeed: "Mach 0.69 aprox.",
    range: "4.000 km aprox.",
    ceiling: "10.600 m aprox.",
    engines: "2 × Rolls-Royce Trent 700",
    crew: "2 pilotos",
    capacity: "Componentes aeronáuticos voluminosos",
    license: "ATPL + Type Rating A330/BelugaXL",
    summary: "Avión de carga volumétrica usado por Airbus para transportar grandes secciones de aeronaves.",
    wikiTitle: "Airbus_BelugaXL"
  },
  {
    slug: "airbus-beluga",
    name: "Airbus Beluga",
    manufacturer: "Airbus",
    country: "Europa",
    use: "Carga",
    category: "Carga volumétrica especial",
    era: "Moderna",
    status: "Activo / reemplazo progresivo",
    firstFlight: "1994",
    maxSpeed: "Mach 0.7 aprox.",
    range: "4.600 km aprox.",
    ceiling: "10.700 m aprox.",
    engines: "2 × turbofán",
    crew: "2 pilotos",
    capacity: "Carga sobredimensionada",
    license: "ATPL + Type Rating especial",
    summary: "Famoso carguero de fuselaje ampliado para transportar partes de aviones Airbus.",
    wikiTitle: "Airbus_Beluga"
  },
  {
    slug: "md-11f",
    name: "McDonnell Douglas MD-11F",
    manufacturer: "McDonnell Douglas / Boeing",
    country: "Estados Unidos",
    use: "Carga",
    category: "Carguero trimotor",
    era: "Moderna",
    status: "Activo en carga / retiro progresivo",
    firstFlight: "1990",
    maxSpeed: "Mach 0.87 aprox.",
    range: "7.300 km aprox. con carga",
    ceiling: "13.100 m aprox.",
    engines: "3 × turbofán",
    crew: "2 pilotos",
    capacity: "Carga aérea intercontinental",
    license: "ATPL + Type Rating MD-11",
    summary: "Trimotor de fuselaje ancho utilizado ampliamente como carguero internacional.",
    wikiTitle: "McDonnell_Douglas_MD-11"
  },

  {
    slug: "t-6-texan-ii",
    name: "Beechcraft T-6 Texan II",
    manufacturer: "Beechcraft",
    country: "Estados Unidos",
    use: "Entrenamiento",
    category: "Entrenador militar turbohélice",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1998",
    maxSpeed: "585 km/h aprox.",
    range: "1.600 km aprox.",
    ceiling: "9.400 m aprox.",
    engines: "1 × Pratt & Whitney Canada PT6",
    crew: "2",
    capacity: "Instructor y alumno",
    license: "Entrenamiento militar",
    summary: "Entrenador militar básico y avanzado usado por varias fuerzas aéreas.",
    wikiTitle: "Beechcraft_T-6_Texan_II"
  },
  {
    slug: "pilatus-pc-21",
    name: "Pilatus PC-21",
    manufacturer: "Pilatus Aircraft",
    country: "Suiza",
    use: "Entrenamiento",
    category: "Entrenador avanzado turbohélice",
    era: "Moderna",
    status: "Activo",
    firstFlight: "2002",
    maxSpeed: "685 km/h aprox.",
    range: "1.300 km aprox.",
    ceiling: "11.500 m aprox.",
    engines: "1 × Pratt & Whitney Canada PT6",
    crew: "2",
    capacity: "Instructor y alumno",
    license: "Entrenamiento militar avanzado",
    summary: "Entrenador turbohélice de alto rendimiento que simula sistemas de avión de combate moderno.",
    wikiTitle: "Pilatus_PC-21"
  },
  {
    slug: "bae-hawk",
    name: "BAE Systems Hawk",
    manufacturer: "BAE Systems",
    country: "Reino Unido",
    use: "Entrenamiento",
    category: "Entrenador avanzado jet",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1974",
    maxSpeed: "1.028 km/h aprox.",
    range: "2.500 km ferry aprox.",
    ceiling: "13.500 m aprox.",
    engines: "1 × turbofán",
    crew: "2",
    capacity: "Entrenamiento avanzado / ataque ligero",
    license: "Entrenamiento militar jet",
    summary: "Jet de entrenamiento avanzado y ataque ligero usado por numerosas fuerzas aéreas.",
    wikiTitle: "BAE_Systems_Hawk"
  },
  {
    slug: "aero-l-39-albatros",
    name: "Aero L-39 Albatros",
    manufacturer: "Aero Vodochody",
    country: "Checoslovaquia / República Checa",
    use: "Entrenamiento",
    category: "Entrenador jet",
    era: "Guerra Fría / Moderna",
    status: "Activo en varios países",
    firstFlight: "1968",
    maxSpeed: "750 km/h aprox.",
    range: "1.100 km aprox.",
    ceiling: "11.500 m aprox.",
    engines: "1 × turbofán",
    crew: "2",
    capacity: "Entrenamiento / ataque ligero",
    license: "Entrenamiento militar jet",
    summary: "Entrenador jet ampliamente exportado y usado también por operadores civiles especializados.",
    wikiTitle: "Aero_L-39_Albatros"
  },
  {
    slug: "yak-130",
    name: "Yakovlev Yak-130",
    manufacturer: "Yakovlev",
    country: "Rusia",
    use: "Entrenamiento",
    category: "Entrenador avanzado / ataque ligero",
    era: "Moderna",
    status: "Activo",
    firstFlight: "1996",
    maxSpeed: "1.060 km/h aprox.",
    range: "2.100 km aprox.",
    ceiling: "12.500 m aprox.",
    engines: "2 × turbofán",
    crew: "2",
    capacity: "Entrenamiento avanzado y cargas externas",
    license: "Entrenamiento militar avanzado",
    summary: "Entrenador avanzado ruso con capacidad de simular comportamiento de cazas modernos.",
    wikiTitle: "Yakovlev_Yak-130"
  },

  {
    slug: "x-15",
    name: "North American X-15",
    manufacturer: "North American Aviation",
    country: "Estados Unidos",
    use: "Experimental",
    category: "Avión cohete hipersónico",
    era: "Guerra Fría / era espacial",
    status: "Retirado / experimental",
    firstFlight: "1959",
    maxSpeed: "Mach 6.7 aprox.",
    range: "Vuelo de prueba",
    ceiling: "100 km+ en vuelos suborbitales",
    engines: "Motor cohete",
    crew: "1",
    capacity: "Instrumentación experimental",
    license: "Piloto de pruebas especializado",
    summary: "Programa experimental que alcanzó velocidades hipersónicas y aportó datos clave para la era espacial.",
    wikiTitle: "North_American_X-15"
  },
  {
    slug: "bell-x-1",
    name: "Bell X-1",
    manufacturer: "Bell Aircraft",
    country: "Estados Unidos",
    use: "Experimental",
    category: "Avión cohete supersónico",
    era: "Posguerra",
    status: "Retirado / experimental",
    firstFlight: "1946",
    maxSpeed: "Mach 1+",
    range: "Vuelo de prueba",
    ceiling: "21.000 m aprox.",
    engines: "Motor cohete",
    crew: "1",
    capacity: "Instrumentación experimental",
    license: "Piloto de pruebas especializado",
    summary: "Aeronave experimental asociada al primer vuelo supersónico tripulado nivelado reconocido.",
    wikiTitle: "Bell_X-1"
  },
  {
    slug: "lockheed-martin-x-59",
    name: "Lockheed Martin X-59 QueSST",
    manufacturer: "Lockheed Martin Skunk Works",
    country: "Estados Unidos",
    use: "Experimental",
    category: "Supersónico silencioso experimental",
    era: "Moderna",
    status: "Experimental",
    firstFlight: "Programa en pruebas",
    maxSpeed: "Mach 1.4 aprox. objetivo",
    range: "Experimental",
    ceiling: "16.800 m aprox. objetivo",
    engines: "1 × turbofán",
    crew: "1",
    capacity: "Instrumentación de pruebas",
    license: "Piloto de pruebas especializado",
    summary: "Demostrador diseñado para estudiar vuelos supersónicos con menor estampido sónico percibido.",
    wikiTitle: "Lockheed_Martin_X-59_QueSST"
  },
  {
    slug: "scaled-composites-spaceshipone",
    name: "SpaceShipOne",
    manufacturer: "Scaled Composites",
    country: "Estados Unidos",
    use: "Experimental",
    category: "Aeronave espacial suborbital",
    era: "Moderna",
    status: "Retirada / histórica",
    firstFlight: "2003",
    maxSpeed: "Supersónica en ascenso cohete",
    range: "Suborbital",
    ceiling: "100 km+",
    engines: "Motor cohete híbrido",
    crew: "1 piloto",
    capacity: "Piloto y espacio para pasajeros según concepto",
    license: "Piloto de pruebas / espacial",
    summary: "Vehículo suborbital privado que ganó el Ansari X Prize y marcó la aviación espacial comercial temprana.",
    wikiTitle: "SpaceShipOne"
  }
];

export const useGroups = ["Todos", "Militar", "Comercial", "Privada / General", "Histórica", "Carga", "Entrenamiento", "Experimental"] as const;

export function getAircraftBySlug(slug: string) {
  return aircraft.find((item) => item.slug === slug);
}

export function countByUse() {
  return useGroups.filter((g) => g !== "Todos").map((group) => ({
    group,
    count: aircraft.filter((item) => item.use === group).length
  }));
}
