import type { Aircraft } from "./types";

export const aircraft: Aircraft[] = [
  { name:"F-22 Raptor", wiki:"F-22 Raptor", group:"Militar", role:"Caza furtivo de superioridad aérea", maker:"Lockheed Martin / Boeing", origin:"Estados Unidos", firstFlight:"1997", status:"Activo", license:"Piloto militar avanzado", engine:"2 Pratt & Whitney F119-PW-100", capacity:"1 piloto", speed:"Mach 2+", range:"aprox. 2.960 km", operators:"Estados Unidos", history:"Diseñado para superioridad aérea moderna. No se exporta y opera principalmente con la Fuerza Aérea de Estados Unidos.", interior:"Cabina monoplaza con pantallas multifunción, aviónica integrada y controles HOTAS." },
  { name:"F-35 Lightning II", wiki:"Lockheed Martin F-35 Lightning II", group:"Militar", role:"Caza furtivo multirrol", maker:"Lockheed Martin", origin:"Estados Unidos", firstFlight:"2006", status:"Activo", license:"Piloto militar avanzado", engine:"1 Pratt & Whitney F135", capacity:"1 piloto", speed:"Mach 1.6", range:"variable según versión", operators:"Estados Unidos, Reino Unido, Italia, Japón, Israel, Australia y otros operadores aliados", history:"Usado para ataque, reconocimiento, defensa aérea y operaciones embarcadas según versión.", interior:"Cabina digital con pantalla panorámica y casco con visualización integrada." },
  { name:"F-16 Fighting Falcon", wiki:"General Dynamics F-16 Fighting Falcon", group:"Militar", role:"Caza multirrol", maker:"General Dynamics / Lockheed Martin", origin:"Estados Unidos", firstFlight:"1974", status:"Activo", license:"Piloto militar avanzado", engine:"Pratt & Whitney F100 o General Electric F110", capacity:"1 piloto", speed:"Mach 2", range:"aprox. 4.200 km ferry", operators:"Estados Unidos, Turquía, Israel, Egipto, Corea del Sur, Grecia y otros", history:"Participó en numerosos conflictos desde finales del siglo XX; es uno de los cazas más exportados.", interior:"Cabina monoplaza con gran visibilidad, HOTAS y aviónica modernizable." },
  { name:"F-15 Eagle", wiki:"McDonnell Douglas F-15 Eagle", group:"Militar", role:"Superioridad aérea", maker:"McDonnell Douglas / Boeing", origin:"Estados Unidos", firstFlight:"1972", status:"Activo", license:"Piloto militar avanzado", engine:"2 Pratt & Whitney F100", capacity:"1 o 2 tripulantes según versión", speed:"Mach 2.5", range:"largo alcance táctico", operators:"Estados Unidos, Japón, Israel, Arabia Saudita, Corea del Sur", history:"Operado en defensa aérea y combate. La variante F-15E se orienta a ataque profundo.", interior:"Cabina orientada a combate aire-aire y ataque, con aviónica modernizada en variantes recientes." },
  { name:"F/A-18 Super Hornet", wiki:"Boeing F/A-18E/F Super Hornet", group:"Militar", role:"Caza embarcado", maker:"Boeing", origin:"Estados Unidos", firstFlight:"1995", status:"Activo", license:"Piloto naval militar", engine:"2 General Electric F414", capacity:"1 o 2 tripulantes", speed:"Mach 1.8", range:"medio alcance embarcado", operators:"Estados Unidos, Australia, Kuwait", history:"Operado desde portaaviones en misiones aire-aire, ataque, escolta y guerra electrónica.", interior:"Cabina naval reforzada para operación embarcada con aviónica de misión." },
  { name:"Eurofighter Typhoon", wiki:"Eurofighter Typhoon", group:"Militar", role:"Caza multirrol", maker:"Eurofighter GmbH", origin:"Europa", firstFlight:"1994", status:"Activo", license:"Piloto militar avanzado", engine:"2 Eurojet EJ200", capacity:"1 piloto", speed:"Mach 2", range:"aprox. 2.900 km ferry", operators:"Reino Unido, Alemania, Italia, España, Arabia Saudita, Qatar", history:"Usado para defensa aérea, interceptación y ataque en fuerzas europeas y aliadas.", interior:"Cabina moderna con pantallas, HOTAS y casco de designación." },
  { name:"Dassault Rafale", wiki:"Dassault Rafale", group:"Militar", role:"Caza multirrol", maker:"Dassault Aviation", origin:"Francia", firstFlight:"1986", status:"Activo", license:"Piloto militar avanzado", engine:"2 Snecma M88", capacity:"1 o 2 tripulantes", speed:"Mach 1.8", range:"aprox. 3.700 km ferry", operators:"Francia, India, Egipto, Qatar, Grecia, Emiratos", history:"Usado en operaciones francesas y exportado como plataforma multirrol de alto nivel.", interior:"Cabina digital con controles HOTAS y aviónica integrada." },
  { name:"C-130 Hercules", wiki:"Lockheed C-130 Hercules", group:"Militar", role:"Transporte táctico", maker:"Lockheed Martin", origin:"Estados Unidos", firstFlight:"1954", status:"Activo", license:"Piloto militar de transporte", engine:"4 Allison T56 turbohélice", capacity:"Carga, tropas o evacuación médica", speed:"aprox. 590 km/h", range:"aprox. 3.800 km", operators:"Estados Unidos y decenas de fuerzas aéreas", history:"Usado en conflictos, operaciones humanitarias, lanzamiento de tropas y transporte táctico.", interior:"Bodega amplia con rampa trasera para carga, vehículos ligeros o camillas." },

  { name:"Airbus A320", wiki:"Airbus A320 family", group:"Comercial", role:"Narrow-body", maker:"Airbus", origin:"Europa", firstFlight:"1987", status:"Activo", license:"ATPL + Type Rating", engine:"CFM56, IAE V2500, LEAP o PW1100G según versión", capacity:"150-186 pasajeros aprox.", speed:"crucero Mach 0.78", range:"corto / medio alcance", operators:"IndiGo, American Airlines, China Eastern, easyJet, Lufthansa y muchos otros", history:"Familia clave para rutas comerciales de corto y medio radio.", interior:"Cabina de pasillo único; cockpit fly-by-wire con side-stick." },
  { name:"Airbus A321neo", wiki:"Airbus A321neo", group:"Comercial", role:"Narrow-body largo alcance", maker:"Airbus", origin:"Europa", firstFlight:"2016", status:"Activo", license:"ATPL + Type Rating", engine:"CFM LEAP-1A o Pratt & Whitney PW1100G", capacity:"hasta más de 200 pasajeros", speed:"crucero Mach 0.78", range:"medio / largo alcance", operators:"American Airlines, Wizz Air, IndiGo, JetBlue, Turkish Airlines", history:"Muy usado para rutas densas y versiones LR/XLR de mayor alcance.", interior:"Cabina de pasillo único, configurable en alta densidad o premium." },
  { name:"Airbus A350", wiki:"Airbus A350", group:"Comercial", role:"Wide-body moderno", maker:"Airbus", origin:"Europa", firstFlight:"2013", status:"Activo", license:"ATPL + Type Rating", engine:"Rolls-Royce Trent XWB", capacity:"300-410 pasajeros aprox.", speed:"crucero Mach 0.85", range:"largo / ultra largo alcance", operators:"Qatar Airways, Singapore Airlines, Cathay Pacific, Delta, Lufthansa", history:"Diseñado para eficiencia en rutas intercontinentales.", interior:"Cabina ancha, iluminación LED, presión y humedad mejoradas." },
  { name:"Airbus A380", wiki:"Airbus A380", group:"Comercial", role:"Wide-body doble cubierta", maker:"Airbus", origin:"Europa", firstFlight:"2005", status:"Activo limitado", license:"ATPL + Type Rating", engine:"Rolls-Royce Trent 900 o Engine Alliance GP7000", capacity:"hasta 853 pasajeros en alta densidad", speed:"crucero Mach 0.85", range:"aprox. 15.000 km", operators:"Emirates es el mayor operador; también Singapore Airlines, British Airways, Qantas", history:"El mayor avión comercial de pasajeros producido en serie.", interior:"Doble cubierta completa; puede incluir suites, bares, duchas y cabinas premium." },
  { name:"Boeing 737", wiki:"Boeing 737", group:"Comercial", role:"Narrow-body", maker:"Boeing", origin:"Estados Unidos", firstFlight:"1967", status:"Activo", license:"ATPL + Type Rating", engine:"JT8D, CFM56 o LEAP según generación", capacity:"120-210 pasajeros aprox.", speed:"crucero Mach 0.78", range:"corto / medio alcance", operators:"Southwest, Ryanair, United, American, Alaska y muchos otros", history:"Una de las familias comerciales más vendidas del mundo.", interior:"Cabina de pasillo único, con múltiples configuraciones de aerolínea." },
  { name:"Boeing 747", wiki:"Boeing 747", group:"Comercial", role:"Wide-body jumbo", maker:"Boeing", origin:"Estados Unidos", firstFlight:"1969", status:"Retirado parcial", license:"ATPL + Type Rating", engine:"JT9D, CF6, RB211 o GEnx según versión", capacity:"366-524 pasajeros aprox.", speed:"crucero Mach 0.85", range:"largo alcance", operators:"Históricamente Pan Am, British Airways, Lufthansa; hoy muy usado en carga", history:"Revolucionó los viajes intercontinentales y marcó la era jumbo.", interior:"Dos pasillos y cubierta superior parcial característica." },
  { name:"Boeing 787 Dreamliner", wiki:"Boeing 787 Dreamliner", group:"Comercial", role:"Wide-body moderno", maker:"Boeing", origin:"Estados Unidos", firstFlight:"2009", status:"Activo", license:"ATPL + Type Rating", engine:"GEnx o Rolls-Royce Trent 1000", capacity:"240-330 pasajeros aprox.", speed:"crucero Mach 0.85", range:"largo alcance", operators:"United, ANA, Qatar Airways, British Airways, Air Canada y otros", history:"Diseñado para rutas punto a punto de largo alcance con alta eficiencia.", interior:"Ventanas grandes, materiales compuestos, humedad y presión mejoradas." },
  { name:"ATR 72", wiki:"ATR 72", group:"Comercial", role:"Turbohélice regional", maker:"ATR", origin:"Francia / Italia", firstFlight:"1988", status:"Activo", license:"ATPL + Type Rating", engine:"2 Pratt & Whitney Canada PW100", capacity:"70 pasajeros aprox.", speed:"aprox. 510 km/h", range:"regional", operators:"IndiGo, Azul, Air New Zealand, FedEx Feeder y operadores regionales", history:"Muy usado en rutas cortas por bajo consumo y operación en aeropuertos regionales.", interior:"Cabina regional de pasillo único y configuración económica." },

  { name:"Cessna 172", wiki:"Cessna 172", group:"Privada / General", role:"Monomotor de entrenamiento y turismo", maker:"Cessna", origin:"Estados Unidos", firstFlight:"1955", status:"Activo", license:"PPL", engine:"Lycoming IO-360 o variantes similares", capacity:"4 personas", speed:"aprox. 226 km/h crucero", range:"aprox. 1.185 km", operators:"Escuelas de vuelo y propietarios privados de todo el mundo", history:"Uno de los aviones más producidos de la historia y base de formación de pilotos.", interior:"Cabina simple de cuatro plazas, ideal para instrucción y vuelos visuales." },
  { name:"Cirrus SR22", wiki:"Cirrus SR22", group:"Privada / General", role:"Monomotor moderno", maker:"Cirrus Aircraft", origin:"Estados Unidos", firstFlight:"2000", status:"Activo", license:"PPL", engine:"Continental IO-550", capacity:"4-5 personas", speed:"aprox. 339 km/h", range:"aprox. 1.900 km", operators:"Propietarios privados, escuelas premium y aviación ejecutiva ligera", history:"Conocido por aviónica moderna y paracaídas balístico CAPS.", interior:"Interior premium con aviónica Garmin y diseño moderno." },
  { name:"Pilatus PC-12", wiki:"Pilatus PC-12", group:"Privada / General", role:"Turbohélice ejecutivo utilitario", maker:"Pilatus", origin:"Suiza", firstFlight:"1991", status:"Activo", license:"CPL / Type Rating según país", engine:"Pratt & Whitney Canada PT6A", capacity:"6-9 pasajeros aprox.", speed:"aprox. 528 km/h", range:"aprox. 3.400 km", operators:"Empresas, servicios médicos, operadores charter y particulares", history:"Valorado por operar en pistas cortas y combinar lujo con capacidad utilitaria.", interior:"Cabina ejecutiva configurable o sanitaria/carga ligera." },
  { name:"Gulfstream G650", wiki:"Gulfstream G650", group:"Privada / General", role:"Jet ejecutivo de ultra largo alcance", maker:"Gulfstream", origin:"Estados Unidos", firstFlight:"2009", status:"Activo", license:"Type Rating", engine:"2 Rolls-Royce BR725", capacity:"hasta 19 pasajeros", speed:"Mach 0.90+", range:"aprox. 12.900 km", operators:"Empresas, gobiernos y propietarios privados de alto nivel", history:"Uno de los jets privados de referencia para vuelos intercontinentales de lujo.", interior:"Cabina amplia con zonas de descanso, trabajo y configuración premium." },

  { name:"Antonov An-225 Mriya", wiki:"Antonov An-225 Mriya", group:"Carga", role:"Carga superpesada", maker:"Antonov", origin:"Ucrania", firstFlight:"1988", status:"Destruido", license:"Tripulación especializada", engine:"6 Ivchenko Progress D-18T", capacity:"carga superpesada", speed:"aprox. 850 km/h", range:"variable con carga", operators:"Antonov Airlines", history:"Fue el avión más pesado del mundo; destruido durante la guerra en Ucrania.", interior:"Bodega enorme para cargas industriales y sobredimensionadas." },
  { name:"Antonov An-124 Ruslan", wiki:"Antonov An-124 Ruslan", group:"Carga", role:"Carga pesada", maker:"Antonov", origin:"Ucrania", firstFlight:"1982", status:"Activo", license:"Tripulación especializada", engine:"4 Ivchenko Progress D-18T", capacity:"carga pesada", speed:"aprox. 865 km/h", range:"largo alcance con carga", operators:"Antonov Airlines, Volga-Dnepr y operadores militares", history:"Usado para transporte de cargas pesadas, ayuda humanitaria y logística militar.", interior:"Bodega de gran volumen con rampa frontal y trasera." },
  { name:"Boeing 747-8F", wiki:"Boeing 747-8", group:"Carga", role:"Carguero wide-body", maker:"Boeing", origin:"Estados Unidos", firstFlight:"2010", status:"Activo", license:"ATPL + Type Rating", engine:"4 GEnx-2B", capacity:"carga aérea de largo alcance", speed:"crucero Mach 0.85", range:"largo alcance", operators:"UPS, Cargolux, Atlas Air, Korean Air Cargo", history:"Versión carguera moderna del 747, muy usada en logística global.", interior:"Bodega principal amplia y nariz abatible en versiones cargueras." },
  { name:"Airbus BelugaXL", wiki:"Airbus BelugaXL", group:"Carga", role:"Carga sobredimensionada", maker:"Airbus", origin:"Europa", firstFlight:"2018", status:"Activo", license:"ATPL + Type Rating", engine:"2 Rolls-Royce Trent 700", capacity:"componentes aeronáuticos voluminosos", speed:"crucero comercial", range:"regional europeo", operators:"Airbus Transport International", history:"Diseñado para transportar secciones de aviones Airbus entre plantas europeas.", interior:"Bodega superior gigantesca para piezas de fuselaje y alas." },

  { name:"Beechcraft T-6 Texan II", wiki:"Beechcraft T-6 Texan II", group:"Entrenamiento", role:"Entrenador turbohélice", maker:"Beechcraft", origin:"Estados Unidos", firstFlight:"1998", status:"Activo", license:"Entrenamiento militar", engine:"Pratt & Whitney Canada PT6A", capacity:"instructor + alumno", speed:"aprox. 585 km/h", range:"entrenamiento", operators:"Estados Unidos, Canadá, Grecia, Israel y otros", history:"Usado para formación básica y avanzada de pilotos militares.", interior:"Cabina biplaza en tándem con instrumentación militar." },
  { name:"Pilatus PC-21", wiki:"Pilatus PC-21", group:"Entrenamiento", role:"Entrenador avanzado", maker:"Pilatus", origin:"Suiza", firstFlight:"2002", status:"Activo", license:"Entrenamiento militar", engine:"Pratt & Whitney Canada PT6A-68B", capacity:"instructor + alumno", speed:"aprox. 685 km/h", range:"entrenamiento", operators:"Suiza, Australia, Francia, Singapur, España y otros", history:"Entrenador moderno que simula perfiles de jet avanzado con menor costo operativo.", interior:"Cabina biplaza con aviónica avanzada y pantallas multifunción." },
  { name:"Aero L-39 Albatros", wiki:"Aero L-39 Albatros", group:"Entrenamiento", role:"Entrenador jet", maker:"Aero Vodochody", origin:"Checoslovaquia", firstFlight:"1968", status:"Activo / histórico", license:"Entrenamiento militar", engine:"Ivchenko AI-25TL", capacity:"2 tripulantes", speed:"aprox. 750 km/h", range:"entrenamiento", operators:"Muchos países de Europa, África, Asia y América", history:"Uno de los entrenadores jet más difundidos del bloque oriental.", interior:"Cabina biplaza en tándem, apta para instrucción avanzada." },

  { name:"Wright Flyer", wiki:"Wright Flyer", group:"Histórica", role:"Pionero", maker:"Wright Company", origin:"Estados Unidos", firstFlight:"1903", status:"Museo", license:"Experimental histórica", engine:"Motor de pistón Wright", capacity:"1 piloto", speed:"muy baja", range:"vuelo experimental", operators:"Hermanos Wright", history:"Primer vuelo controlado y motorizado reconocido de la historia.", interior:"No tenía cabina cerrada; estructura abierta y control primitivo." },
  { name:"Supermarine Spitfire", wiki:"Supermarine Spitfire", group:"Histórica", role:"Caza WWII", maker:"Supermarine", origin:"Reino Unido", firstFlight:"1936", status:"Histórico operativo", license:"Licencia histórica", engine:"Rolls-Royce Merlin o Griffon", capacity:"1 piloto", speed:"aprox. 594 km/h según versión", range:"variable", operators:"Reino Unido y aliados", history:"Participó en la Segunda Guerra Mundial, especialmente asociado a la Batalla de Inglaterra.", interior:"Cabina estrecha de caza clásico con instrumentación analógica." },
  { name:"P-51 Mustang", wiki:"North American P-51 Mustang", group:"Histórica", role:"Caza WWII", maker:"North American Aviation", origin:"Estados Unidos", firstFlight:"1940", status:"Histórico operativo", license:"Licencia histórica", engine:"Packard V-1650 Merlin", capacity:"1 piloto", speed:"aprox. 700 km/h", range:"largo alcance para escolta", operators:"Estados Unidos, Reino Unido y aliados", history:"Clave como escolta de bombarderos aliados en la Segunda Guerra Mundial.", interior:"Cabina de caza con gran visibilidad y mandos analógicos." },
  { name:"Douglas DC-3", wiki:"Douglas DC-3", group:"Histórica", role:"Clásico comercial", maker:"Douglas", origin:"Estados Unidos", firstFlight:"1935", status:"Histórico operativo", license:"CPL / ATPL", engine:"2 Pratt & Whitney R-1830 o Wright R-1820", capacity:"21-32 pasajeros aprox.", speed:"aprox. 333 km/h", range:"regional", operators:"Aerolíneas históricas y operadores civiles/militares", history:"Transformó el transporte aéreo comercial y tuvo versión militar C-47.", interior:"Cabina clásica de pasajeros con configuración vintage." },

  { name:"Bell X-1", wiki:"Bell X-1", group:"Experimental", role:"Supersónico experimental", maker:"Bell Aircraft", origin:"Estados Unidos", firstFlight:"1946", status:"Museo", license:"Piloto de pruebas", engine:"Motor cohete Reaction Motors XLR11", capacity:"1 piloto", speed:"supersónico", range:"pruebas", operators:"NACA / USAF", history:"Primer avión tripulado en superar oficialmente la barrera del sonido.", interior:"Cabina experimental mínima para piloto de pruebas." },
  { name:"North American X-15", wiki:"North American X-15", group:"Experimental", role:"Hipersonico experimental", maker:"North American Aviation", origin:"Estados Unidos", firstFlight:"1959", status:"Museo", license:"Piloto de pruebas", engine:"Motor cohete XLR99", capacity:"1 piloto", speed:"hipersónico", range:"vuelos de investigación", operators:"NASA / USAF", history:"Alcanzó velocidades y altitudes extremas, aportando datos para programas espaciales.", interior:"Cabina presurizada experimental con traje especial de piloto." },
  { name:"X-59 QueSST", wiki:"Lockheed Martin X-59 QueSST", group:"Experimental", role:"Supersónico silencioso", maker:"Lockheed Martin / NASA", origin:"Estados Unidos", firstFlight:"2024", status:"Experimental", license:"Piloto de pruebas", engine:"General Electric F414", capacity:"1 piloto", speed:"supersónico", range:"pruebas", operators:"NASA", history:"Programa para estudiar vuelos supersónicos con menor estampido sónico.", interior:"Cabina experimental con sistema de visión externa por cámaras." },
  { name:"SpaceShipOne", wiki:"SpaceShipOne", group:"Experimental", role:"Suborbital", maker:"Scaled Composites", origin:"Estados Unidos", firstFlight:"2003", status:"Museo", license:"Piloto de pruebas", engine:"Motor cohete híbrido", capacity:"1 piloto", speed:"suborbital", range:"vuelos de prueba", operators:"Scaled Composites", history:"Primer vehículo tripulado privado en alcanzar el espacio suborbital reconocido.", interior:"Cabina compacta experimental para vuelo suborbital." }
];
