import { type Aircraft } from "./types";

export const aircraft4: Aircraft[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // AUTOGIROS — 12 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════
  { name:"AutoGyro Calidus", wiki:"AutoGyro Calidus", group:"Autogiros", role:"Autogiro deportivo de cabina abierta", maker:"AutoGyro GmbH", origin:"Alemania", firstFlight:"2009", status:"Activo", license:"Licencia de ultraligero / autogiro", engine:"1 Rotax 914 UL de 115hp", capacity:"2 personas en tándem", speed:"máx. 160 km/h", range:"aprox. 600 km", operators:"Pilotos privados en Europa, Australia y América Latina", history:"El Calidus es uno de los autogiros más populares del mundo, fabricado en Hildesheim, Alemania. Con su rotor libre autorotante y hélice propulsora trasera, es imposible que sufra pérdida de sustentación incluso si el motor falla. Miles de unidades operan en más de 50 países.", registryId:"AG-006", productionApprox:1200 },

  { name:"Magni Gyro M-16 Tandem Trainer", wiki:"Magni Gyro", group:"Autogiros", role:"Autogiro de entrenamiento biplaza en tándem", maker:"Magni Gyro S.r.l.", origin:"Italia", firstFlight:"2003", status:"Activo", license:"Licencia de autogiro / ultraligero", engine:"1 Rotax 912 ULS de 100hp", capacity:"2 personas en tándem", speed:"máx. 140 km/h", range:"aprox. 500 km", operators:"Escuelas de vuelo de autogiro en Europa, China y Australia", history:"La empresa italiana Magni Gyro es uno de los fabricantes líderes mundiales de autogiros. El M-16 Tandem Trainer está diseñado específicamente para instrucción, con dobles controles y asientos en tándem. Es el autogiro de entrenamiento más usado en escuelas de vuelo de Europa.", registryId:"AG-007", productionApprox:400 },

  { name:"Cierva C.19", wiki:"Cierva C.19", group:"Autogiros", role:"Autogiro de la era pionera, primer modelo de producción", maker:"A.V. Roe & Company (Avro) bajo licencia Cierva", origin:"Reino Unido", firstFlight:"1927", status:"Museo", license:"N/A (histórico)", engine:"1 Armstrong Siddeley Mongoose de 100hp", capacity:"1 piloto", speed:"aprox. 145 km/h", range:"aprox. 350 km", operators:"RAF (evaluación), civil en Europa y EE.UU.", history:"El Cierva C.19 fue el primer autogiro fabricado en serie por Avro en el Reino Unido, basado en los inventos del español Juan de la Cierva. Era un biplano con rotor superior libre que prevenía la pérdida de sustentación, algo revolucionario en los años 20. Sentó las bases de todos los autogiros modernos.", registryId:"AG-008" },

  { name:"Bensen B-8M Gyrocopter", wiki:"Bensen B-8", group:"Autogiros", role:"Autogiro ultraligero de construcción casera", maker:"Bensen Aircraft Company (kit)", origin:"Estados Unidos", firstFlight:"1955", status:"Activo (kitplanes históricos)", license:"Licencia de ultraligero (EAA)", engine:"1 McCulloch o Volkswagen de 72-90hp (montado push)", capacity:"1 piloto", speed:"máx. 120 km/h", range:"aprox. 200 km", operators:"Entusiastas de la aviación experimental en EE.UU., Reino Unido y Europa", history:"Igor Bensen creó el Gyrocopter más sencillo y barato de la historia: un autogiro que cualquier persona podía construir en su garaje con 500 dólares en los años 60. El B-8M usaba un motor push de moto de nieve. Popularizó la aviación ultraligera y todavía se vuelan cientos de ejemplares.", registryId:"AG-009", productionApprox:3000 },

  { name:"Xenon RST", wiki:"Xenon (autogyro)", group:"Autogiros", role:"Autogiro deportivo polaco de alto rendimiento", maker:"Przedsiębiorstwo Innowacyjno-Wdrożeniowe (PIW Xenon)", origin:"Polonia", firstFlight:"2005", status:"Activo", license:"Licencia de ultraligero SPL-G", engine:"1 Rotax 914 UL de 115hp o Rotax 912 de 100hp", capacity:"2 personas en tándem", speed:"máx. 155 km/h", range:"aprox. 550 km", operators:"Pilotos deportivos en Europa Central, UK y Rusia", history:"El Xenon es el autogiro más destacado de la industria aeronáutica polaca. Su diseño moderno con cabina semiabierta y rotor de dos palas lo convierte en uno de los más ágiles del mercado. Polonia tiene una tradición centenaria en aviación ligera que incluye los famosos planeadores SZD.", registryId:"AG-010", productionApprox:250 },

  { name:"ELA Aviacion ELA-07", wiki:"ELA Aviacion", group:"Autogiros", role:"Autogiro deportivo español de clase ultraligero", maker:"ELA Aviacion S.L.", origin:"España", firstFlight:"2007", status:"Activo", license:"Licencia de ultraligero (ULM) en Europa", engine:"1 Rotax 912 ULS de 100hp o Rotax 914 de 115hp", capacity:"2 personas side-by-side o tándem según versión", speed:"máx. 140 km/h", range:"aprox. 500 km", operators:"Escuelas de vuelo y propietarios privados en España, Francia, Alemania y Argentina", history:"ELA Aviacion es la empresa española líder en fabricación de autogiros. El ELA-07 fue diseñado en Albacete para cumplir las normas europeas de ultraligeros. España tiene una conexión especial con los autogiros ya que Juan de la Cierva los inventó allí en 1919.", registryId:"AG-011", productionApprox:300 },

  { name:"Sportcopter Vortex", wiki:"Sportcopter", group:"Autogiros", role:"Autogiro deportivo norteamericano de cabina abierta", maker:"Sportcopter LLC", origin:"Estados Unidos", firstFlight:"2001", status:"Activo", license:"Licencia de ultraligero o piloto privado (FAA)", engine:"1 Rotax 912 de 80-100hp", capacity:"1 piloto", speed:"máx. 130 km/h", range:"aprox. 400 km", operators:"Entusiastas del vuelo deportivo en EE.UU. y Canadá", history:"Sportcopter es uno de los pocos fabricantes estadounidenses de autogiros ligeros. El Vortex fue diseñado para que pilotos con licencia de avión ultraligero pudieran transitar fácilmente al autogiro. En EE.UU. la aviación de construcción casera y deporte es enormemente popular con más de 300.000 aeronaves registradas.", registryId:"AG-012", productionApprox:150 },

  { name:"Rotorsport Cavalon Pro", wiki:"AutoGyro Cavalon", group:"Autogiros", role:"Autogiro de cabina cerrada con cabina climatizada", maker:"AutoGyro GmbH / Rotorsport UK", origin:"Alemania / Reino Unido", firstFlight:"2012", status:"Activo", license:"Licencia de autogiro (NPPL en UK) o ULM", engine:"1 Rotax 914 UL de 115hp", capacity:"2 personas side-by-side", speed:"máx. 160 km/h", range:"aprox. 650 km", operators:"Propietarios privados en Reino Unido, Alemania, Australia, España y Nueva Zelanda", history:"El Cavalon Pro es la versión mejorada del exitoso Cavalon original, con cabina cerrada que ofrece confort en cualquier clima. Rotorsport UK es el distribuidor oficial en el Reino Unido donde los autogiros gozan de enorme popularidad. Su configuración side-by-side permite vuelo compartido para instrucción o turismo.", registryId:"AG-013", productionApprox:600 },

  { name:"Aviomania G1sb", wiki:"Aviomania", group:"Autogiros", role:"Autogiro biplaza italiano de fuselaje tubular", maker:"Aviomania S.r.l.", origin:"Italia", firstFlight:"2008", status:"Activo", license:"Licencia de ultraligero (ULM)", engine:"1 Rotax 912 ULS de 100hp", capacity:"2 personas en tándem", speed:"máx. 130 km/h", range:"aprox. 450 km", operators:"Escuelas de vuelo de autogiro en Italia, España, Grecia y Brasil", history:"Aviomania es un fabricante italiano de autogiros ligeros. El G1sb es notable por su estructura de fuselaje tubular de acero con recubrimiento de tela, lo que lo hace fácil de reparar y mantener. Italia tiene una tradición de fabricar aeronaves ligeras accesibles y es uno de los mayores mercados de ultraligeros de Europa.", registryId:"AG-014", productionApprox:180 },

  { name:"Niviuk Autogiro", wiki:"Niviuk", group:"Autogiros", role:"Autogiro ligero de diseño español reciente", maker:"Niviuk Paragliders / Autogirocataluña", origin:"España", firstFlight:"2015", status:"En desarrollo / Activo limitado", license:"Licencia de ultraligero (ULM-G)", engine:"1 Rotax 912 ULS de 100hp", capacity:"2 personas en tándem", speed:"máx. 120 km/h", range:"aprox. 350 km", operators:"Pilotos experimentales en España y sur de Europa", history:"Niviuk, conocida principalmente por sus parapentes, colaboró en el desarrollo de un autogiro ligero catalán. España mantiene una industria activa de autogiros ligeros como homenaje al legado de Juan de la Cierva. El proyecto refleja el interés europeo por vehículos aéreos lentos y versátiles para zonas montañosas.", registryId:"AG-015" },

  { name:"Air Command 532 Elite", wiki:"Air Command International", group:"Autogiros", role:"Autogiro kit americano de bajo costo", maker:"Air Command International", origin:"Estados Unidos", firstFlight:"1983", status:"Activo (vintage)", license:"Licencia experimental EAA o ultraligero FAA Part 103", engine:"1 Rotax 532 de 65hp o motores similares de 50-80hp", capacity:"1 piloto (algunos modelos 2)", speed:"máx. 110 km/h", range:"aprox. 300 km", operators:"Constructores y propietarios de kits experimentales en EE.UU. y Canadá", history:"Air Command International popularizó los autogiros de kit en los años 80 con diseños simples y económicos. El 532 Elite fue uno de los más vendidos por su facilidad de construcción, idealmente en 200 horas. Cientos de unidades siguen volando en los cielos norteamericanos cada fin de semana.", registryId:"AG-016", productionApprox:800 },

  { name:"Cierva C.30 (original)", wiki:"Cierva C.30", group:"Autogiros", role:"Primer autogiro práctico de producción en serie (1931)", maker:"Lioré et Olivier / CASA / Avro (bajo licencia Cierva)", origin:"España / Francia / Reino Unido", firstFlight:"1931", status:"Museo (algunos ejemplares conservados)", license:"N/A (histórico)", engine:"1 Armstrong Siddeley Genet Major I de 105hp (versión inicial)", capacity:"2 personas (piloto + pasajero)", speed:"aprox. 177 km/h máx.", range:"aprox. 459 km", operators:"Civil y militar en UK, Francia, Alemania, EE.UU., España (WWII)", history:"El Cierva C.30 fue el primer autogiro fabricado en verdadera producción en serie, con más de 143 unidades construidas en tres países. La RAF los usó para calibrar radares durante la Segunda Guerra Mundial ya que podían volar a velocidades muy bajas sin caer. Juan de la Cierva, su inventor, murió en 1936.", registryId:"AG-017", productionApprox:143 },

  // ══════════════════════════════════════════════════════════════════════════
  // RESCATE — 12 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════
  { name:"Sikorsky S-76", wiki:"Sikorsky S-76", group:"Rescate", role:"Helicóptero de rescate y transporte ejecutivo bimotores", maker:"Sikorsky Aircraft (Lockheed Martin)", origin:"Estados Unidos", firstFlight:"1977", status:"Activo", license:"ATPL helicóptero + Type Rating S-76", engine:"2 Pratt & Whitney Canada PT6B-36A de 732shp c/u", capacity:"12-13 pasajeros o configuración HEMS médica", speed:"aprox. 287 km/h", range:"aprox. 748 km", operators:"HEMS en UK, Irlanda, Noruega, Malasia; servicio offshore en el Mar del Norte; emergencias médicas, Venezuela, varios países latinoamericanos", history:"El Sikorsky S-76 es uno de los helicópteros bimotor más exitosos del mercado, fabricado desde 1979. En versión de rescate y HEMS (Helicopter Emergency Medical Services) opera en los hospitales más avanzados de Europa. La familia real británica lo usó para vuelos privados. Su sucesor S-76D usa motores Pratt & Whitney PW210S.", registryId:"RS-009", productionApprox:850 },

  { name:"Airbus H145 (Rescate)", wiki:"Airbus H145", group:"Rescate", role:"Helicóptero de rescate montañero y HEMS de referencia", maker:"Airbus Helicopters (Leonardo / Kawasaki)", origin:"Alemania / Francia", firstFlight:"1999 (EC145)", status:"Activo", license:"ATPL helicóptero + Type Rating H145", engine:"2 Turbomeca Arriel 2E de 894shp c/u (H145 actual)", capacity:"9 pasajeros o configuración HEMS con 2 médicos + 1 paciente", speed:"aprox. 268 km/h", range:"aprox. 680 km", operators:"DRF Luftrettung (Alemania), Rega (Suiza), ÖAMTC (Austria), Air Zermatt, Babcock (UK), guardias civiles en España y Francia, múltiples servicios HEMS en 30+ países", history:"El H145 es el helicóptero de rescate montañero y HEMS más utilizado del mundo. Los rescatistas de los Alpes suizos, los Pirineos y los Dolomitas dependen de él para operaciones en altitudes extremas. Su sistema de rotor coaxial sin cola (Fenestron) lo hace más silencioso y seguro en entornos urbanos.", registryId:"RS-010", productionApprox:1500 },

  { name:"Bell 429 GlobalRanger", wiki:"Bell 429", group:"Rescate", role:"Helicóptero ligero de rescate y policía de tecnología avanzada", maker:"Bell Helicopter Textron", origin:"Canadá / Estados Unidos", firstFlight:"2007", status:"Activo", license:"ATPL helicóptero + Type Rating Bell 429", engine:"2 Pratt & Whitney Canada PW207D1 de 673shp c/u", capacity:"7 pasajeros o configuración EMS con médico + paciente", speed:"aprox. 287 km/h", range:"aprox. 722 km", operators:"Policía de Irlanda, FAA (EE.UU.), emergencias en Corea, Australia, Japón, varios servicios HEMS en Europa y Asia-Pacífico", history:"El Bell 429 es el helicóptero policial y de emergencias médicas de nueva generación de Bell. Su aviónica Garmin G2000H digital de última generación permite operaciones IFR en condiciones meteorológicas adversas. La Garda Síochána irlandesa lo usa para operaciones de rescate marítimo.", registryId:"RS-011", productionApprox:250 },

  { name:"AgustaWestland AW169", wiki:"Leonardo AW169", group:"Rescate", role:"Helicóptero de rescate y misiones especiales mediano", maker:"Leonardo / AgustaWestland", origin:"Italia", firstFlight:"2012", status:"Activo", license:"ATPL helicóptero + Type Rating AW169", engine:"2 Pratt & Whitney Canada PW210A de 900shp c/u", capacity:"10 pasajeros o configuración SAR/HEMS", speed:"aprox. 310 km/h", range:"aprox. 833 km", operators:"HEMS en UK (Bond Aviation, Babcock), Policía del Estado italiano, servicio de guardia costera en Kazajistán y Azerbaiyán, emergencias en Arabia Saudita", history:"El AW169 es el helicóptero mediano de nueva generación de Leonardo que combina máxima flexibilidad de misión con aviónica de última generación. El Servicio Nacional de Salud del Reino Unido lo emplea ampliamente en misiones HEMS. Su diseño de cabina modular permite reconfigurarlo en horas para diferentes misiones.", registryId:"RS-012", productionApprox:200 },

  { name:"Boeing Vertol 107 / Sea Knight", wiki:"Boeing Vertol 107", group:"Rescate", role:"Helicóptero de transporte y rescate naval de rotor en tándem", maker:"Boeing Vertol", origin:"Estados Unidos", firstFlight:"1958", status:"Activo limitado (Japón) / Retirado (EE.UU.)", license:"ATPL helicóptero tipo pesado", engine:"2 General Electric T58-GE-16 de 1.870shp c/u", capacity:"25 tropas o 15 camillas o 4.500 kg de carga interior", speed:"aprox. 267 km/h", range:"aprox. 1.000 km", operators:"US Navy (retirado 2004), US Marines (retirado), Japón (aún activo como KV-107), Suecia, España (Naval)", history:"El Sea Knight con sus rotores en tándem fue el helicóptero de rescate naval estándar de EE.UU. durante 40 años. Sus dos rotores superpuestos en frente y atrás eliminan la necesidad de rotor de cola. Japón aún opera versiones fabricadas bajo licencia por Kawasaki. Participó en Vietnam, Malvinas (Argentina) y el Golfo Pérsico.", registryId:"RS-013", productionApprox:624 },

  { name:"Canadair CL-215 (SAR/Extinción)", wiki:"Canadair CL-215", group:"Rescate", role:"Hidroavión anfibio para extinción de incendios y rescate marítimo", maker:"Canadair Ltd.", origin:"Canadá", firstFlight:"1967", status:"Activo (algunos)", license:"ATPL + habilitación hidros/anfibio", engine:"2 Pratt & Whitney R-2800-83AM de 2.100hp c/u (pistón)", capacity:"tanque de 5.455 litros de agua o 10 personas en rescate", speed:"aprox. 359 km/h", range:"aprox. 2.167 km", operators:"Quebec (Canadá), España, Francia, Grecia, Yugoslavia (retirado), Tailandia, Italia", history:"El Canadair CL-215 fue el primer hidroavión diseñado desde cero específicamente para extinción de incendios, a diferencia de los conversiones anteriores. Puede recoger 5.000 litros de agua rasando un lago en 12 segundos. El CL-215 también se usa en rescate marítimo costero gracias a su capacidad de amerizar.", registryId:"RS-014", productionApprox:125 },

  { name:"Piasecki HUP Retriever", wiki:"Piasecki HUP Retriever", group:"Rescate", role:"Helicóptero de rescate naval histórico de pequeño tamaño", maker:"Piasecki Helicopter Corporation", origin:"Estados Unidos", firstFlight:"1948", status:"Museo (retirado)", license:"N/A (histórico)", engine:"1 Continental R-975-46 de 550hp", capacity:"4 personas o 2 camillas", speed:"aprox. 170 km/h", range:"aprox. 560 km", operators:"US Navy, US Marine Corps, Ejército de EE.UU., Marina de Canadá y Francia", history:"El HUP Retriever fue el primer helicóptero de rescate naval en servicio con la US Navy, incorporándose a los portaaviones en 1949. Su configuración de rotores en tándem (delantero y trasero) eliminaba el rotor de cola para poder operar en hangarines reducidos de buques de guerra. Rescató pilotos caídos en los primeros años de la aviación naval de la Guerra Fría.", registryId:"RS-015", productionApprox:70 },

  { name:"Kaman HH-43 Huskie", wiki:"Kaman HH-43 Huskie", group:"Rescate", role:"Helicóptero de rescate contra incendios en bases aéreas", maker:"Kaman Aircraft Corporation", origin:"Estados Unidos", firstFlight:"1956", status:"Retirado (1988)", license:"N/A (retirado)", engine:"1 Lycoming T53-L-13B de 860shp", capacity:"3 tripulantes + 2 rescatados", speed:"aprox. 193 km/h", range:"aprox. 489 km", operators:"USAF, US Navy, US Marine Corps, Irán, Colombia, Marruecos, Pakistán, Tailandia", history:"El Huskie fue el helicóptero de rescate contra incendios estándar de las bases aéreas de la USAF durante 25 años. Su configuración con dos rotores intermesclados en X (synchropter) es única en Kaman: los rotores se entrecruzan sin chocarse, eliminando el rotor de cola. Realizó miles de rescates de pilotos en accidentes en bases aéreas de todo el mundo.", registryId:"RS-016", productionApprox:263 },

  { name:"Sikorsky SH-60 Seahawk (SAR)", wiki:"Sikorsky SH-60 Seahawk", group:"Rescate", role:"Helicóptero naval de búsqueda y rescate antisubmarino", maker:"Sikorsky Aircraft", origin:"Estados Unidos", firstFlight:"1979", status:"Activo", license:"ATPL helicóptero militar naval", engine:"2 General Electric T700-GE-701C de 1.870shp c/u", capacity:"4 tripulantes + 4 rescatados o camillas", speed:"aprox. 270 km/h", range:"aprox. 833 km", operators:"US Navy, Marina de Australia, España, Japón, Grecia, Turquía, Arabia Saudita, y 20+ marinas mundiales", history:"El Seahawk es la versión naval del célebre Black Hawk del Ejército. En misiones de rescate SAR, opera desde fragatas y destructores para rescatar náufragos y pilotos en el mar. La variante MH-60R es la más avanzada del mundo en búsqueda y rescate naval. La Armada Argentina lo usa también.", registryId:"RS-017", productionApprox:900 },

  { name:"Leonardo AW101 Merlin", wiki:"AgustaWestland AW101", group:"Rescate", role:"Helicóptero pesado de rescate y misiones SAR de larga distancia", maker:"Leonardo / AgustaWestland (GKN-Westland + Agusta)", origin:"Reino Unido / Italia", firstFlight:"1987", status:"Activo", license:"ATPL helicóptero pesado + Type Rating AW101", engine:"3 General Electric CT7-8E de 2.270shp c/u", capacity:"30 tropas o 16 camillas o equipos SAR completos", speed:"aprox. 309 km/h", range:"aprox. 1.000 km", operators:"RAF (MSAR/SAR), Marina Real de Portugal (SAR), Marina de Canadá, Dinamarca, Japón, Noruega, Italia y 8+ países", history:"El AW101 Merlin es el helicóptero de rescate SAR más capaz de Europa. La RAF lo opera exclusivamente para misiones de búsqueda y rescate en el Atlántico Norte y el Mar del Norte. Portugal lo usa para rescates oceánicos en el Atlántico. Su capacidad de volar en condiciones severas de hielo y tormenta lo hace único.", registryId:"RS-018", productionApprox:250 },

  { name:"DHC-6 Twin Otter (Rescate / SAR)", wiki:"De Havilland Canada DHC-6 Twin Otter", group:"Rescate", role:"Avión de rescate y transporte en zonas remotas", maker:"De Havilland Canada / Viking Air", origin:"Canadá", firstFlight:"1965", status:"Activo", license:"CPL/ATPL + habilitación turbohélice", engine:"2 Pratt & Whitney Canada PT6A-27 de 620shp c/u", capacity:"19 pasajeros o camillas + equipo médico en versión MEDEVAC", speed:"aprox. 338 km/h", range:"aprox. 1.705 km", operators:"Cruz Roja, ICRC, ONU, Antártica (múltiples agencias), STOL en islas Maldivas, Nepal, Papua Nueva Guinea, servicios SAR en países árticos", history:"El Twin Otter es el avión de rescate y transporte humanitario más versátil del mundo. Puede despegar y aterrizar en pistas de 200 metros, o sobre agua, nieve o hielo. La Cruz Roja lo usa en zonas de guerra y desastre. Viking Air de Canadá reinició su producción en 2010 y aún fabrica nuevas unidades.", registryId:"RS-019", productionApprox:900 },

  { name:"Aerospatiale SA 365 Dauphin", wiki:"Eurocopter AS365 Dauphin", group:"Rescate", role:"Helicóptero de rescate costero y HEMS mediano", maker:"Aérospatiale / Eurocopter (Airbus Helicopters)", origin:"Francia", firstFlight:"1972", status:"Activo", license:"ATPL helicóptero + Type Rating Dauphin", engine:"2 Turbomeca Arriel 2C1 de 858shp c/u", capacity:"10-13 pasajeros o 2 camillas en versión HEMS", speed:"aprox. 296 km/h", range:"aprox. 870 km", operators:"USCG (HH-65 Dolphin), servicio de rescate costero en Francia, China (offshore), South Korea, Brasil (SAR), Argentina (Prefectura Naval)", history:"El Dauphin / Dolphin es el helicóptero de rescate costero estándar del US Coast Guard desde 1980, operando desde Miami a Alaska. Francia lo usa para rescates marítimos en el Atlántico y el Mediterráneo. Argentina lo usa en su servicio de guardacostas para el Río de la Plata y el Atlántico Sur.", registryId:"RS-020", productionApprox:1000 },

  // ══════════════════════════════════════════════════════════════════════════
  // PLANEADORES — 12 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════
  { name:"Alexander Schleicher ASW 27", wiki:"Schleicher ASW 27", group:"Planeadores", role:"Planeador de clase libre y 15m de máximas prestaciones", maker:"Alexander Schleicher GmbH & Co.", origin:"Alemania", firstFlight:"1996", status:"Activo", license:"SPL (Licencia de Planeador)", engine:"Ninguno", capacity:"1 piloto", speed:"máx. 285 km/h", range:"1.200+ km en condiciones óptimas (L/D 48:1)", operators:"Pilotos de competición FAI clase libre y 15m en todo el mundo", history:"El ASW 27 es considerado por muchos el planeador monoplaza más equilibrado jamás fabricado. Su envergadura de 15 metros con winglets lo hace competitivo tanto en clase 15m como en clase libre. Múltiples campeones del mundo de la FAI han volado el ASW 27 en los Campeonatos del Mundo de Vuelo a Vela.", registryId:"PL-012", productionApprox:400 },

  { name:"Jonker Sailplanes JS1 Revelation", wiki:"Jonker Sailplanes JS1", group:"Planeadores", role:"Planeador de clase libre de las más altas prestaciones", maker:"Jonker Sailplanes (Pty) Ltd.", origin:"Sudáfrica", firstFlight:"2009", status:"Activo", license:"SPL", engine:"Ninguno (versión JS1C tiene motor auxiliar)", capacity:"1 piloto", speed:"máx. 290 km/h", range:"1.500+ km en condiciones excepcionales (L/D 52:1)", operators:"Campeones mundiales de vuelo a vela en Alemania, Argentina, EE.UU., Australia y Sudáfrica", history:"El JS1 Revelation de Jonker Sailplanes fue una revelación cuando llegó de Sudáfrica: una empresa africana compitiendo con los mejores fabricantes europeos. Con una eficiencia aerodinámica L/D de 52:1 y winglets de alta tecnología, ha ganado múltiples campeonatos internacionales. Demostró que la innovación en planeadores viene de cualquier parte del mundo.", registryId:"PL-013", productionApprox:150 },

  { name:"SZD-55-1 Promyk", wiki:"SZD-55", group:"Planeadores", role:"Planeador polaco de clase estándar de competición", maker:"PZL Szybowcowy Zakład Doświadczalny (SZD)", origin:"Polonia", firstFlight:"1988", status:"Activo", license:"SPL", engine:"Ninguno", capacity:"1 piloto", speed:"máx. 260 km/h", range:"700+ km en condiciones favorables", operators:"Pilotos de competición FAI en Polonia, Europa Central y América Latina", history:"Polonia tiene una de las tradiciones más ricas del mundo en vuelo a vela, con campeonatos del mundo ganados desde los años 30. El SZD-55 Promyk (Rayo de Sol) es el planeador de competición clase estándar más exitoso de Polonia. La fábrica SZD en Bielsko-Biała lleva décadas fabricando planeadores exportados a todo el mundo.", registryId:"PL-014", productionApprox:200 },

  { name:"Glasflügel 304", wiki:"Glasflügel 304", group:"Planeadores", role:"Planeador de clase estándar con fibra de vidrio pionera", maker:"Glasflügel GmbH", origin:"Alemania", firstFlight:"1975", status:"Activo (veterano)", license:"SPL", engine:"Ninguno", capacity:"1 piloto", speed:"máx. 250 km/h", range:"600+ km en condiciones favorables", operators:"Pilotos de competición y recreativos en Europa, EE.UU. y Australia", history:"Glasflügel fue un pionero en el uso de fibra de vidrio para planeadores en los años 60-70. El Glasflügel 304 es considerado uno de los primeros planeadores modernos de clase estándar con perfil de ala laminar optimizado para altas velocidades. Su diseño influyó en todos los planeadores de competición fabricados después.", registryId:"PL-015", productionApprox:250 },

  { name:"Schempp-Hirth Nimbus 4", wiki:"Schempp-Hirth Nimbus-4", group:"Planeadores", role:"Planeador de clase abierta con mayor envergadura del mundo (26,4m)", maker:"Schempp-Hirth Flugzeugbau GmbH", origin:"Alemania", firstFlight:"1991", status:"Activo", license:"SPL", engine:"Ninguno (versión T: motor retráctil)", capacity:"1 piloto (DT: 2 en tándem)", speed:"máx. 280 km/h", range:"2.000+ km en día excepcional (L/D 60:1)", operators:"Élite mundial de pilotos de vuelo a vela en competición de clase abierta FAI", history:"El Nimbus 4 con sus 26,4 metros de envergadura es el planeador no motorizado más eficiente jamás fabricado. Una razón de planeo de 60:1 significa que avanza 60 metros por cada metro que desciende. En los Alpes o en los Andes, pilotos experimentados han volado más de 1.500 km en un solo día sin motor.", registryId:"PL-016", productionApprox:180 },

  { name:"DG Flugzeugbau DG-808", wiki:"DG Flugzeugbau DG-808", group:"Planeadores", role:"Planeador motovelero clase 15m de alto rendimiento", maker:"DG Flugzeugbau GmbH", origin:"Alemania", firstFlight:"1996", status:"Activo", license:"SPL + habilitación motovelero", engine:"1 Wankel DG-505 de 37hp (retráctil)", capacity:"1 piloto", speed:"máx. 270 km/h", range:"1.000+ km en vuelo a vela / autónomo con motor", operators:"Pilotos de vuelo a vela en Europa Central, Escandinavia y Australia", history:"El DG-808 es un motovelero de la clase 15m que ofrece lo mejor de dos mundos: el rendimiento de un planeador de competición con la seguridad de un motor auxiliar retráctil para regresar a casa si el tiempo empeora. DG Flugzeugbau es uno de los fabricantes de planeadores más innovadores de Alemania.", registryId:"PL-017", productionApprox:300 },

  { name:"Centrair 201 Marianne", wiki:"Centrair 201 Marianne", group:"Planeadores", role:"Planeador francés de club para instrucción y placer", maker:"Centrair S.A.", origin:"Francia", firstFlight:"1980", status:"Activo (veterano)", license:"SPL (en instrucción)", engine:"Ninguno", capacity:"1 piloto", speed:"máx. 230 km/h", range:"Variable (vuelo local de aeroclube)", operators:"Aeroclubes de vuelo a vela en Francia, Bélgica, España y algunos países latinoamericanos", history:"La Marianne fue fabricada por la empresa francesa Centrair para satisfacer la demanda de aeroclubes que necesitaban un planeador de entrenamiento económico y de fácil manejo. Francia tiene una tradición de vuelo a vela fuertemente ligada a la aviación deportiva rural. La Marianne introdujo a miles de franceses al placer del vuelo sin motor.", registryId:"PL-018", productionApprox:350 },

  { name:"PZL SZD-50 Puchacz", wiki:"SZD-50 Puchacz", group:"Planeadores", role:"Planeador biplaza de instrucción y acrobacia en tándem", maker:"PZL Szybowcowy Zakład Doświadczalny", origin:"Polonia", firstFlight:"1979", status:"Activo", license:"SPL (instrucción, primer solo)", engine:"Ninguno", capacity:"2 personas en tándem", speed:"máx. 210 km/h", range:"Variable (instrucción)", operators:"Aeroclubes de instrucción en Polonia, Alemania, República Checa, España, Argentina y 20+ países", history:"El Puchacz (Búho en polaco) es el planeador de instrucción biplaza más exitoso de Europa del Este. Fabricado desde 1979, más de 250 unidades operan en aeroclubes de todo el mundo. Su estructura robusta de metal permite maniobras acrobáticas, ideal para que los alumnos practiquen recuperaciones de situaciones anómalas.", registryId:"PL-019", productionApprox:250 },

  { name:"Schempp-Hirth Discus-2c", wiki:"Schempp-Hirth Discus", group:"Planeadores", role:"Planeador monoplaza de clase estándar y 15m más vendido", maker:"Schempp-Hirth Flugzeugbau GmbH", origin:"Alemania", firstFlight:"1994 (Discus-2)", status:"Activo", license:"SPL", engine:"Ninguno (versión b tiene motor auxiliar)", capacity:"1 piloto", speed:"máx. 270 km/h", range:"800+ km en vuelo a vela (L/D 44:1)", operators:"Pilotos de competición y recreativos en todo el mundo; uno de los planeadores más vendidos de la historia", history:"El Discus-2c es el planeador estándar más popular del mercado desde que reemplazó al Discus-b en 1994. Su combinación de alto rendimiento, buen comportamiento de vuelo y precio razonable lo convirtió en el favorito de los pilotos de competición de nivel nacional. Schempp-Hirth lo sigue fabricando y vendiendo con gran éxito décadas después de su lanzamiento.", registryId:"PL-020", productionApprox:800 },

  { name:"Grob G 103 Twin Astir II", wiki:"Grob G 103 Twin Astir", group:"Planeadores", role:"Planeador biplaza de instrucción y turismo", maker:"Grob Aircraft AG", origin:"Alemania", firstFlight:"1976", status:"Activo", license:"SPL (instrucción)", engine:"Ninguno", capacity:"2 personas side-by-side", speed:"máx. 220 km/h", range:"Variable (instrucción / turismo)", operators:"Aeroclubes de instrucción en Alemania, EE.UU., Australia, Sudáfrica y América Latina", history:"El Twin Astir de Grob fue el planeador biplaza side-by-side de instrucción más popular de los años 80-90. Su disposición side-by-side permite al instructor ver y comunicarse naturalmente con el alumno. Grob Aircraft, además de planeadores, fabrica los aviones de entrenamiento primario G 120 para fuerzas aéreas militares.", registryId:"PL-021", productionApprox:600 },

  { name:"Rolladen-Schneider LS4", wiki:"Rolladen-Schneider LS4", group:"Planeadores", role:"Planeador de clase estándar clásico con enorme popularidad", maker:"Rolladen-Schneider Flugzeugwerke", origin:"Alemania", firstFlight:"1980", status:"Activo", license:"SPL", engine:"Ninguno", capacity:"1 piloto", speed:"máx. 250 km/h", range:"700+ km en condiciones favorables", operators:"Pilotos de competición y aeroclubes en Europa, EE.UU., Sudáfrica, Australia y Argentina", history:"El LS4 es probablemente el planeador monoplaza más exitoso de todos los tiempos en términos de número de campeonatos ganados. Introducido en 1980, dominó la clase estándar FAI durante más de una década. Muchos aeroclubes argentinos tienen LS4 en su flota para instrucción avanzada. Su sucesor, el LS8, también tiene esa misma magia.", registryId:"PL-022", productionApprox:1000 },

  { name:"Lange Antares 20E", wiki:"Lange Aviation Antares", group:"Planeadores", role:"Motovelero eléctrico de clase libre de máximas prestaciones", maker:"Lange Aviation GmbH", origin:"Alemania", firstFlight:"2003", status:"Activo", license:"SPL + habilitación motovelero", engine:"1 motor eléctrico de 42kW con batería de litio-ion (propulsor eléctrico)", capacity:"1 piloto", speed:"máx. 280 km/h", range:"1.200+ km en vuelo a vela / 50km con motor eléctrico", operators:"Pilotos avanzados de vuelo a vela en Europa, especialmente en Alemania y Austria", history:"El Antares 20E fue el primer planeador de clase libre con motor eléctrico del mundo, precursor de la aviación eléctrica moderna. Su motor eléctrico silencioso se usa solo para despegar o regresar si la meteorología empeora. La envergadura de 20 metros con winglets modernos le da una eficiencia aerodinámica extraordinaria.", registryId:"PL-023", productionApprox:80 },

  // ══════════════════════════════════════════════════════════════════════════
  // DEPORTIVOS / ULTRALIGEROS — 10 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════
  { name:"Pipistrel Panthera", wiki:"Pipistrel Panthera", group:"Deportivos / Ultraligeros", role:"Avión de turismo compuesto de alta eficiencia con opción eléctrica", maker:"Pipistrel d.o.o.", origin:"Eslovenia", firstFlight:"2012", status:"Certificación en curso", license:"PPL + IFR", engine:"1 Lycoming IO-390 de 215hp (versión convencional) o eléctrico", capacity:"4 personas", speed:"aprox. 337 km/h (tope de clase)", range:"aprox. 2.000 km (convencional)", operators:"Pilotos privados en Europa y EE.UU. (pedidos)", history:"El Panthera de Pipistrel es el avión de cuatro plazas más eficiente del mundo en su clase. Esta empresa eslovena es pionera en aviación eléctrica certificada, habiendo fabricado el primer avión eléctrico aprobado por EASA. El Panthera combina velocidad de crucero comparable a un turbohélice con el consumo de un avión más pequeño.", registryId:"DU-016", productionApprox:50 },

  { name:"Cirrus SR20", wiki:"Cirrus SR20", group:"Deportivos / Ultraligeros", role:"Avión privado con paracaídas balístico de seguridad activa", maker:"Cirrus Aircraft", origin:"Estados Unidos", firstFlight:"1995", status:"Activo", license:"PPL", engine:"1 Continental IO-360-ES de 200hp", capacity:"4 personas", speed:"aprox. 282 km/h", range:"aprox. 1.319 km", operators:"Propietarios privados en EE.UU., Europa y América Latina; escuelas de vuelo de aviación privada", history:"El Cirrus SR20 fue el primer avión de producción en serie con un sistema de paracaídas balístico completo (CAPS) para toda la aeronave. En caso de emergencia, el piloto tira de un mango y el avión entero baja colgado de un paracaídas. Este concepto ha salvado más de 100 vidas. La familia SR es el avión privado más vendido del mundo.", registryId:"DU-017", productionApprox:7000 },

  { name:"Tecnam P2002 Sierra", wiki:"Tecnam P2002 Sierra", group:"Deportivos / Ultraligeros", role:"Avión de deporte ligero italiano de ala baja", maker:"Costruzioni Aeronautiche Tecnam S.p.A.", origin:"Italia", firstFlight:"2000", status:"Activo", license:"LSA (Light Sport Aircraft) / ULM", engine:"1 Rotax 912 ULS de 100hp", capacity:"2 personas side-by-side", speed:"máx. 245 km/h", range:"aprox. 1.000 km", operators:"Escuelas de vuelo y propietarios privados en más de 40 países", history:"Tecnam es el fabricante italiano de aviación general más exitoso del mundo, con más de 8.000 aviones vendidos. El P2002 Sierra es un ala baja elegante que ofrece el manejo de un avión deportivo de alto rendimiento con la economía de un motor Rotax. Italia y España son los mayores mercados europeos para este tipo de avión.", registryId:"DU-018", productionApprox:1200 },

  { name:"Blackshape Prime", wiki:"Blackshape Prime", group:"Deportivos / Ultraligeros", role:"Avión deportivo italiano en fibra de carbono de máxima performance", maker:"Blackshape Aircraft s.r.l.", origin:"Italia", firstFlight:"2010", status:"Activo", license:"LSA / ULM avanzado", engine:"1 Rotax 912 iS Sport de 100hp", capacity:"2 personas side-by-side", speed:"máx. 300 km/h", range:"aprox. 1.200 km", operators:"Pilotos deportivos avanzados en Europa, Medio Oriente y EE.UU.", history:"El Blackshape Prime es el avión LSA más rápido del mundo, con una velocidad máxima de 300 km/h gracias a su fuselaje completamente en fibra de carbono. Fabricado en Monopoli (Puglia), Italia, es considerado el Ferrari de los ultraligeros. La USAF lo evaluó para instrucción básica bajo el programa T-X.", registryId:"DU-019", productionApprox:200 },

  { name:"Just Aircraft SuperSTOL XL", wiki:"Just Aircraft SuperSTOL", group:"Deportivos / Ultraligeros", role:"Avión bush STOL extremo para pistas sin preparar", maker:"Just Aircraft LLC", origin:"Estados Unidos", firstFlight:"2011", status:"Activo", license:"LSA o experimental EAA", engine:"1 Rotax 912 ULS de 100hp o Rotax 915 iS de 141hp", capacity:"2 personas side-by-side", speed:"máx. 185 km/h", range:"aprox. 900 km", operators:"Pilotos de bush aviation en Alaska, Canadá, Argentina, Nueva Zelanda y África", history:"El SuperSTOL XL puede despegar y aterrizar en menos de 30 metros gracias a sus largas alas de alta sustentación y flaps de doble ranura. Es el rey del bush flying moderno, capaz de operar en playas, barrancos, praderas y montañas. En Alaska y Patagonia, este tipo de avión es el vínculo entre comunidades sin carreteras.", registryId:"DU-020", productionApprox:400 },

  { name:"Zenith STOL CH 701", wiki:"Zenith Aircraft CH 701", group:"Deportivos / Ultraligeros", role:"Avión STOL ultraligero de construcción amateur", maker:"Zenith Aircraft Company (kit)", origin:"Canadá / Estados Unidos", firstFlight:"1986", status:"Activo", license:"LSA o experimental EAA (kit)", engine:"1 Rotax 503 de 50hp o Jabiru 2200 de 85hp", capacity:"2 personas side-by-side", speed:"máx. 145 km/h", range:"aprox. 600 km", operators:"Constructores amateurs en EE.UU., Canadá, Australia, Sudáfrica y Argentina", history:"El Zenith CH 701 es uno de los kits de avión STOL más populares del mundo, diseñado para que un aficionado lo construya en su garaje en 1.000 horas. Con sus aletas deflectoras en el borde de ataque del ala puede despegar en 60 metros. La comunidad EAA (Experimental Aircraft Association) en EE.UU. tiene más de 200.000 miembros constructores.", registryId:"DU-021", productionApprox:2000 },

  { name:"Kolb Twinstar Mk.III", wiki:"Kolb Aircraft", group:"Deportivos / Ultraligeros", role:"Ultraligero biplaza de ala alta de construcción económica", maker:"Kolb Aircraft Co.", origin:"Estados Unidos", firstFlight:"1982", status:"Activo", license:"LSA o ultraligero FAA Part 103", engine:"1 Rotax 447 de 40hp o Rotax 503 de 50hp", capacity:"2 personas side-by-side", speed:"máx. 130 km/h", range:"aprox. 500 km", operators:"Entusiastas de la aviación ultraligera en EE.UU. y Europa", history:"La empresa Kolb Aircraft de Pennsylvania es sinónimo de aviación ultraligera asequible en EE.UU. El Twinstar permite que cualquier persona vuele legalmente sin licencia de piloto en EE.UU. bajo la Part 103 (aviones bajo 254 kg y velocidades máximas de 113 km/h). Los kits Kolb han introducido a miles de personas al vuelo deportivo.", registryId:"DU-022", productionApprox:1500 },

  { name:"Kitfox Series 7 Super Sport", wiki:"Kitfox Aircraft", group:"Deportivos / Ultraligeros", role:"Avión kit de backcountry y bush para terreno difícil", maker:"Kitfox Aircraft LLC", origin:"Estados Unidos", firstFlight:"1984 (Serie 1)", status:"Activo", license:"LSA o experimental EAA", engine:"1 Rotax 912 ULS de 100hp o Superior/Lycoming de 115-180hp", capacity:"2 personas side-by-side", speed:"máx. 225 km/h", range:"aprox. 1.000 km", operators:"Pilotos de backcountry aviation en EE.UU., Canadá, Argentina y Nueva Zelanda", history:"El Kitfox es uno de los kits de avión más vendidos del mundo con más de 7.000 kits distribuidos. Su diseño de ala de armazón de tela le da un peso mínimo y capacidad STOL para los campos más remotos. La comunidad backcountry aviation en EE.UU. lo considera uno de los pilares del flying libre en la naturaleza.", registryId:"DU-023", productionApprox:7000 },

  { name:"CGS Hawk Arrow II", wiki:"CGS Hawk", group:"Deportivos / Ultraligeros", role:"Avión ultraligero trike-style de construcción simple", maker:"CGS Aviation", origin:"Estados Unidos", firstFlight:"1982", status:"Activo (veterano)", license:"Ultraligero FAA Part 103 (sin licencia) o LSA", engine:"1 Rotax 447 de 40hp o 503 de 52hp", capacity:"1-2 personas", speed:"máx. 130 km/h", range:"aprox. 400 km", operators:"Entusiastas de aviación deportiva en EE.UU., Canadá y Europa Oriental", history:"El CGS Hawk fue uno de los primeros ultraligeros de EE.UU. en popularizar el vuelo sin licencia bajo la FAA Part 103. Chuck Slusarczyk de Ohio diseñó un avión que cualquier persona podía ensamblar en días y volar sin entrenamiento formal. Representa la filosofía americana de libertad de vuelo que existe desde Kitty Hawk.", registryId:"DU-024", productionApprox:1200 },

  { name:"Dova DV-1 Skylark", wiki:"Dova Aircraft DV-1 Skylark", group:"Deportivos / Ultraligeros", role:"Avión microligero checo de ala baja económico", maker:"Dova Aircraft s.r.o.", origin:"República Checa", firstFlight:"2005", status:"Activo", license:"LSA (ELSA en Europa) / ULM", engine:"1 Rotax 912 ULS de 100hp", capacity:"2 personas side-by-side", speed:"máx. 240 km/h", range:"aprox. 1.000 km", operators:"Escuelas de vuelo y pilotos privados en Europa Central, UK, Francia y España", history:"La República Checa tiene una industria aeronáutica ligera de enorme tradición, exportando aviones como los Zlin, L-39 Albatros y actualmente los LSA modernos. El Skylark de Dova es un ejemplo de la calidad checa en aviación ligera: construcción en fibra de vidrio, aviónica moderna y precio competitivo. Se usa ampliamente en aeroclubes europeos de instrucción básica.", registryId:"DU-025", productionApprox:300 },

  // ══════════════════════════════════════════════════════════════════════════
  // ENTRENAMIENTO — 8 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════
  { name:"Grob G 120TP", wiki:"Grob G 120TP", group:"Entrenamiento", role:"Entrenador primario y básico turbohélice alemán", maker:"Grob Aircraft AG", origin:"Alemania", firstFlight:"2004", status:"Activo", license:"Piloto militar básico / PPL militar", engine:"1 Pratt & Whitney Canada PT6A-25A de 509shp", capacity:"2 tripulantes en tándem", speed:"aprox. 556 km/h", range:"aprox. 1.420 km", operators:"Fuerza Aérea Alemana (Luftwaffe), RAF (evaluación), Portugal, Australia (RAAF evaluación), Jamaica", history:"El Grob G 120TP es el entrenador primario turbohélice de la Luftwaffe alemana, usado para enseñar las habilidades básicas de vuelo antes de pasar al Eurofighter. Con su cockpit digital y motor turbohélice, prepara a los cadetes para la transición a jets de combate modernos. Grob Aircraft en Mindelheim fabrica tanto planeadores como entrenadores militares.", registryId:"EN-025", productionApprox:100 },

  { name:"Hongdu JL-10 / L-15 Falcon", wiki:"Hongdu L-15", group:"Entrenamiento", role:"Entrenador avanzado chino con capacidad de ataque ligero", maker:"Hongdu Aviation Industry Corporation (HAIG)", origin:"China", firstFlight:"2006", status:"Activo", license:"Piloto militar avanzado jet chino", engine:"2 AI-222K-25F de 4.200 kgf c/u (versión básica)", capacity:"2 tripulantes en tándem", speed:"Mach 1.6", range:"aprox. 3.100 km ferry", operators:"Fuerza Aérea del Ejército Popular de Liberación (PLAAF), Zambia, considerado por varios países africanos y asiáticos", history:"El L-15 Falcon es el entrenador avanzado de nueva generación de China, diseñado para reemplazar el JJ-7 (MiG-21U). Desarrollado con asistencia técnica de Yakovlev de Rusia, puede superar Mach 1.4 y lleva a los pilotos chinos desde entrenamiento básico hasta cabinas de cuarta generación. Zambia fue el primer cliente de exportación.", registryId:"EN-026", productionApprox:120 },

  { name:"AIDC AT-3 Tzu Chung", wiki:"AIDC AT-3", group:"Entrenamiento", role:"Entrenador avanzado jet de fabricación taiwanesa", maker:"Aerospace Industrial Development Corporation (AIDC)", origin:"Taiwán", firstFlight:"1980", status:"Activo (reducido)", license:"Piloto militar avanzado", engine:"2 Garrett TFE731-2-2L de 1.559 kgf c/u", capacity:"2 tripulantes en tándem", speed:"aprox. 900 km/h", range:"aprox. 2.300 km", operators:"Fuerza Aérea de la República de China (Taiwán)", history:"El AT-3 Tzu Chung (Autodesarrollo) fue el primer avión de reacción diseñado y fabricado íntegramente en Taiwán. AIDC lo desarrolló en los años 70 para demostrar la capacidad aeronáutica nacional. Se usó para entrenar a los pilotos del F-104 Starfighter y F-5E Tiger II. Taiwán continuó con el programa IDF Ching-Kuo (caza propio) basándose en esta experiencia.", registryId:"EN-027", productionApprox:62 },

  { name:"Aermacchi M-345 HET", wiki:"Aermacchi M-345", group:"Entrenamiento", role:"Entrenador avanzado ligero italiano de bajo costo operativo", maker:"Leonardo / Aermacchi", origin:"Italia", firstFlight:"2011", status:"Activo", license:"Piloto militar básico jet", engine:"1 Williams International FJ44-4M-34 de 1.950 kgf", capacity:"2 tripulantes en tándem", speed:"aprox. 830 km/h", range:"aprox. 1.900 km", operators:"Aeronautica Militare Italiana (reemplazando al MB-339)", history:"El M-345 HET (High Efficiency Trainer) fue diseñado para reemplazar al exitoso MB-339 en la Aeronautica Militare Italiana. Usa un único motor Williams FJ44 en lugar de los dos motores del M-346, reduciendo costos de operación. Su cabina glass cockpit prepara a cadetes italianos para transición a Eurofighter y F-35. Italia combina diseño civil (Lamborghini, Ferrari) con excelencia aeronáutica.", registryId:"EN-028", productionApprox:25 },

  { name:"Alenia Aermacchi M-311", wiki:"Aermacchi M-311", group:"Entrenamiento", role:"Entrenador básico jet italiano para fuerzas aéreas pequeñas", maker:"Leonardo / Alenia Aermacchi", origin:"Italia", firstFlight:"2005", status:"Activo (producción limitada)", license:"Piloto militar básico jet", engine:"1 Williams International FJ44-2C de 1.340 kgf", capacity:"2 tripulantes en tándem", speed:"aprox. 780 km/h", range:"aprox. 1.900 km", operators:"Fuerza Aérea italiana (evaluación), clientes internacionales evaluando como sustituto del MB-326", history:"El M-311 de Alenia Aermacchi fue diseñado como entrenador básico jet económico para fuerzas aéreas con presupuestos limitados que operaban el legendario MB-326. Su motor monoreactor Williams consume la mitad de combustible que los bimotores. Italia tiene una larga historia de fabricar entrenadores exitosos que van desde el MB-326 al M-346.", registryId:"EN-029", productionApprox:15 },

  { name:"Beechcraft T-6C Texan II (versión naval)", wiki:"Beechcraft T-6 Texan II", group:"Entrenamiento", role:"Entrenador básico naval turbohélice de la US Navy", maker:"Beechcraft / Raytheon / Textron Aviation", origin:"Estados Unidos", firstFlight:"1998 (T-6A)", status:"Activo", license:"Piloto naval básico", engine:"1 Pratt & Whitney Canada PT6A-68 de 1.100shp", capacity:"2 tripulantes en tándem", speed:"aprox. 584 km/h", range:"aprox. 1.658 km", operators:"US Navy / US Marine Corps (T-6C), además de Grecia, Irak, Marruecos, México, Israel, Canadá y 15+ países", history:"El T-6C Texan II es la versión naval mejorada del T-6A con aviónica glass cockpit actualizada. La US Navy lo usa en Corpus Christi, Texas, para el entrenamiento básico de pilotos que luego pasan a los T-45 Goshawk y F/A-18. El nombre Texan II rinde homenaje al legendario North American T-6 Texan de la Segunda Guerra Mundial.", registryId:"EN-030", productionApprox:1000 },

  { name:"Yakovlev Yak-152", wiki:"Yakovlev Yak-152", group:"Entrenamiento", role:"Entrenador primario turbohélice ruso de nueva generación", maker:"Yakovlev Design Bureau / Irkut", origin:"Rusia", firstFlight:"2016", status:"Activo (producción inicial)", license:"Piloto militar básico", engine:"1 VOKBM M-14X de 500hp (radial) o Rybinsk TVD-50A", capacity:"2 tripulantes side-by-side", speed:"aprox. 500 km/h", range:"aprox. 1.200 km", operators:"Fuerza Aerospacial Rusa (reemplaza Yak-52)", history:"El Yak-152 es el reemplazo ruso del veterano Yak-52 para instrucción primaria militar. A diferencia del Yak-52 con asientos en tándem, el Yak-152 tiene asientos side-by-side para facilitar la instrucción inicial. Rusia necesitaba modernizar su flota de entrenadores básicos, muchos de los cuales datan de los años 70-80.", registryId:"EN-031", productionApprox:30 },

  { name:"Pilatus PC-9", wiki:"Pilatus PC-9", group:"Entrenamiento", role:"Entrenador básico y avanzado turbohélice suizo", maker:"Pilatus Aircraft Ltd.", origin:"Suiza", firstFlight:"1984", status:"Activo", license:"Piloto militar básico avanzado", engine:"1 Pratt & Whitney Canada PT6A-62 de 950shp", capacity:"2 tripulantes en tándem", speed:"aprox. 593 km/h", range:"aprox. 1.642 km", operators:"Fuerza Aérea Suiza, Australia (Pilatus PC-9/A como base del T-6), Arabia Saudita, Tailandia, Chipre, Jordania, Myanmar, Eslovenia, Alemania, y 15+ países", history:"El PC-9 fue tan exitoso que sirvió de base para el Beechcraft T-6 Texan II americano: Raytheon/Beechcraft lo adquirió en licencia para el contrato JPATS de la USAF. La fábrica suiza Pilatus en Stans fabricó el PC-9 hasta 2002 pero su legado vive en miles de T-6 activos en todo el mundo hoy.", registryId:"EN-032", productionApprox:260 },

];
