import { type Aircraft } from "./types";

export const aircraft5: Aircraft[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // HELICÓPTEROS ADICIONALES — 16 nuevas entradas
  // ══════════════════════════════════════════════════════════════════════════

  { name:"Bell AH-1Z Viper", wiki:"Bell AH-1Z Viper", group:"Helicópteros", role:"Helicóptero de ataque del Cuerpo de Marines — el Cobra del siglo XXI", maker:"Bell Textron", origin:"Estados Unidos", firstFlight:"2000", status:"Activo", license:"Piloto militar de helicóptero de ataque", engine:"2 General Electric T700-GE-401C de 1.828shp c/u", capacity:"2 tripulantes (piloto + artillero) en tándem", speed:"aprox. 296 km/h", range:"aprox. 685 km", operators:"US Marine Corps, República Checa, Bahrein, Pakistán", history:"El AH-1Z Viper es la versión definitiva del legendario HueyCobra, el primer helicóptero de ataque de producción del mundo (1967). El 'Zulu Cobra' comparte el 85% de componentes con el UH-1Y Venom. Su rotor de 4 palas sin bisagras y sensores Target Sight System (TSS) lo hacen devastador. El Marine Corps lo usa como su único helicóptero de ataque, a diferencia del Ejército que usa el Apache.", interior:"Cabina tándem en tándem (artillero adelante, piloto atrás), pantallas digitales EFIS, casco HMDS para designación de objetivos.", weapons:"Cañón M197 Gatling de 20mm (3 cañones rotativos, 750 disparos), misiles Hellfire, Sidewinder AIM-9X, rockets Hydra 70" },

  { name:"Bell AH-1W SuperCobra", wiki:"Bell AH-1W SuperCobra", group:"Helicópteros", role:"Helicóptero de ataque bimotór del Marine Corps — predecesor del Viper", maker:"Bell Helicopter Textron", origin:"Estados Unidos", firstFlight:"1983", status:"Retirado (reemplazado por AH-1Z)", license:"Piloto militar", engine:"2 General Electric T700-GE-401 de 1.690shp c/u", capacity:"2 tripulantes en tándem", speed:"aprox. 282 km/h", range:"aprox. 518 km", operators:"US Marine Corps (retirado), Turquía, Taiwán, Irán (pre-revolución)", history:"El SuperCobra fue el primer helicóptero de ataque bimotór operacional del mundo. Participó en la Guerra del Golfo (1991), Somalia e Irak. En la noche del 24 de enero de 1991, SuperCobras destruyeron 2 lanchas iraquíes en el primer combate aeronaval de helicópteros de la historia. Turquía lo fabricó bajo licencia como T129 ATAK.", interior:"Cabina tándem angosta (solo 97cm de ancho) para reducir perfil frontal y blancos.", weapons:"Cañón M197 de 20mm, misiles TOW/Hellfire, Sidewinder AIM-9L, rockets 70mm" },

  { name:"Sikorsky CH-53K King Stallion", wiki:"Sikorsky CH-53K King Stallion", group:"Helicópteros", role:"El helicóptero más pesado del mundo occidental — sucesor del Super Stallion", maker:"Sikorsky Aircraft (Lockheed Martin)", origin:"Estados Unidos", firstFlight:"2015", status:"Activo (introducción 2022)", license:"Piloto militar avanzado", engine:"3 General Electric T408-GE-400 de 7.500shp c/u (total: 22.500shp)", capacity:"55 soldados o 27.000 kg en gancho exterior", speed:"aprox. 315 km/h", range:"aprox. 925 km", operators:"US Marine Corps (primer operador), Israel (S-33 Nachshon en evaluación)", history:"El CH-53K puede levantar casi el doble que su predecesor CH-53E: 27.000 kg externos. Eso equivale a tres Humvees simultáneamente. Su aviónica fly-by-wire, cabina de vidrio digital y materiales compuestos lo hacen la aeronave de levantamiento pesado más avanzada del mundo. El Marine Corps planea 200 unidades para reemplazar toda la flota CH-53E.", interior:"Cabina digital de cuatro pantallas multifunción, rotor de composite de 24m, sistema de reabastecimiento en vuelo.", weapons:"Ametralladoras defensivas M240 en rampas y ventanas" },

  { name:"Boeing AH-64E Apache Guardian", wiki:"Boeing AH-64 Apache", group:"Helicópteros", role:"La versión más avanzada del Apache — rey de los helicópteros de ataque", maker:"Boeing Defense, Space & Security", origin:"Estados Unidos", firstFlight:"2011", status:"Activo", license:"Piloto militar avanzado de helicóptero de ataque", engine:"2 General Electric T700-GE-701D de 1.994shp c/u", capacity:"2 tripulantes (piloto + copiloto/artillero)", speed:"aprox. 293 km/h", range:"aprox. 476 km", operators:"EE.UU., Reino Unido, Israel, Países Bajos, India, Japón, Grecia, Arabia Saudita, EAU, Egipto, Taiwán, Singapur, Marruecos", history:"El Apache Guardian puede enlazarse digitalmente con drones UAV tipo MQ-1C Gray Eagle y controlar hasta seis simultáneamente — actúa como 'helicóptero madre'. El Reino Unido los usó en Irak y Afganistán. Israel desarrolló el modelo Saraf con aviónica nacional. La India los llama 'Prachand' (feroz). 2.400+ construidos en total (todas versiones).", interior:"Cabina tándem con sistema TADS/PNVS (sensores día/noche), display montado en casco (IHADSS) — donde mira el artillero, ahí apunta el cañón.", weapons:"Cañón M230E1 de 30mm (1.200 rpm), 16 misiles Hellfire Longbow, 76 rockets Hydra/APKWS, misiles Stinger AIM-92" },

  { name:"Bell UH-1H Iroquois (Huey)", wiki:"Bell UH-1 Iroquois", group:"Helicópteros", role:"El símbolo del Vietnam — 16.000 construidos", maker:"Bell Helicopter Textron", origin:"Estados Unidos", firstFlight:"1956", status:"Activo (en muchos países)", license:"Licencia de helicóptero militar o civil", engine:"1 Lycoming T53-L-13B de 1.100shp (turboeje)", capacity:"2 pilotos + 8-13 soldados o 4 camillas", speed:"aprox. 237 km/h", range:"aprox. 507 km", operators:"EE.UU. (Vietnam), Australia, Alemania, Argentina, Italia, Tailandia, Filipinas, 70+ países", history:"El sonido del rotor del Huey es el símbolo sonoro de la Guerra de Vietnam. Más de 16.000 construidos — el helicóptero más producido de la historia tras el Mi-8. Sirvió como transporte, artillado, medevac y rescate. El piloto más joven de EE.UU. (14 años, Gerald Young) voló un Huey en Vietnam. Argentina los usó en las Malvinas para transporte y rescate.", interior:"Cabina semiabierta característica con puertas corredizas laterales, asientos laterales plegables para tropas, espacio central para camillas.", weapons:"(Versión armada) 2 ametralladoras M60 en puertas, rockets 2.75 pulgadas, M5 Grenade Launcher" },

  { name:"Bell 412 EP", wiki:"Bell 412", group:"Helicópteros", role:"Helicóptero utilitario civil y militar bimotór de 13 plazas", maker:"Bell Textron / Bell Helicopter Canada", origin:"Canadá / Estados Unidos", firstFlight:"1979", status:"Activo", license:"CPL-H + Type Rating", engine:"2 Pratt & Whitney Canada PT6T-3D Twin Pac de 1.342shp total", capacity:"2 pilotos + 13 pasajeros", speed:"aprox. 259 km/h", range:"aprox. 656 km", operators:"Policía de Chile, Colombia, Venezuela, Indonesia, Italia (HEMS), US DEA, fuerzas militares de 40+ países", history:"El Bell 412 es la versión cuadripala del Bell 212, con rotor de composites que reduce vibración y ruido. La versión EP tiene aviónica digital. La policía antidrogas latinoamericana lo usa masivamente. Indonesia lo fabrica bajo licencia como PTDI NB-412. La Cruz Roja Argentina los usa en zonas remotas.", interior:"Cabina de 13 plazas con acceso bilateral, configuración HEMS con UCI aérea o carga." },

  { name:"Kamov Ka-27 Helix / Ka-28", wiki:"Kamov Ka-27", group:"Helicópteros", role:"Helicóptero naval antisubmarino soviético/ruso de rotor coaxial", maker:"Kamov Design Bureau / Russian Helicopters", origin:"URSS / Rusia", firstFlight:"1973", status:"Activo", license:"Piloto naval de helicóptero", engine:"2 Isotov TV3-117KM de 2.200shp c/u", capacity:"3 tripulantes (piloto + operador sonar + operador táctil)", speed:"aprox. 270 km/h", range:"aprox. 800 km", operators:"Rusia (Armada), India (Ka-28), Vietnam, Siria, Yemen, China (Ka-28), Kazajistán, Ucrania", history:"El Ka-27 es el helicóptero naval estándar de la Marina Rusa, embarcado en cruceros, destructores y portaaviones del Almirante Kuznetsov. Su diseño coaxial (sin rotor de cola) es compacto para hangares navales. La India opera la variante Ka-28 desde sus fragatas Talwar y Shivalik. En la guerra de Ucrania los Ka-27 rusos operaron en el Mar Negro.", interior:"Bodega compacta con sonar dipping VGS-3, torpedos APR-2E, sonoboyas y sistema MAD para detección de submarinos.", weapons:"Torpedos APR-2E de 400mm, cargas de profundidad PLAB-250-120, misiles antisubmarinos" },

  { name:"Mil Mi-4 Hound", wiki:"Mil Mi-4", group:"Helicópteros", role:"El primer helicóptero de transporte soviético — copia mejorada del Sikorsky S-55", maker:"Mil Moscow Helicopter Plant", origin:"URSS", firstFlight:"1952", status:"Retirado (museos)", license:"N/A", engine:"1 Shvetsov ASh-82V de 1.700hp (pistón radial)", capacity:"1 piloto + 11-12 soldados o 1.600 kg de carga", speed:"aprox. 175 km/h", range:"aprox. 465 km", operators:"URSS (Aeroflot, VVS), China (Harbin Z-5), Vietnam, Alemania Oriental, Egipto, Afganistán", history:"Stalin ordenó el desarrollo del Mi-4 en 1951 tras ver el Sikorsky H-19 de EE.UU. en Corea. En solo 12 meses, Mil produjo el prototipo. Se fabricaron más de 3.500 unidades. China lo copió como el Harbin Z-5 y produjo miles más. En la crisis de Cuba (1962), los Mi-4 de la URSS eran visibles en las fotos U-2. El Aeroflot los usó para conectar aldeas siberianas inaccesibles.", interior:"Bodega trasera con rampa de carga, cabina del piloto en la punta del morro (vista panorámica inusual)." },

  { name:"Sikorsky S-64 Skycrane (CH-54 Tarhe)", wiki:"Sikorsky S-64 Skycrane", group:"Helicópteros", role:"Helicóptero grúa aérea — sin fuselaje, pura potencia de elevación", maker:"Sikorsky Aircraft / Erickson Inc.", origin:"Estados Unidos", firstFlight:"1962", status:"Activo (civil)", license:"ATPL helicóptero pesado + Type Rating S-64", engine:"2 Pratt & Whitney JFTD12A de 4.500shp c/u", capacity:"3 tripulantes (piloto, copiloto, operador de carga)", speed:"aprox. 203 km/h", range:"aprox. 370 km", operators:"Erickson Air-Crane (helicóptero contra incendios), US Army (CH-54, retirado), varios países para construcción", history:"El Skycrane no tiene fuselaje convencional — es una armadura de acero con dos turbinas en la cima y tren de aterrizaje de zancos altos que permite posicionarse sobre cargas. En Vietnam como CH-54 Tarhe recuperó más de 380 aeronaves derribadas detrás de líneas enemigas. Hoy Erickson los usa para combate aéreo de incendios forestales con tanques de agua de 10.000 litros.", interior:"Silla del operador de carga en posición invertida (mirando hacia atrás y abajo) para control de izado de precisión." },

  { name:"Airbus H160", wiki:"Airbus H160", group:"Helicópteros", role:"El helicóptero bimotór mediano del siglo XXI — tecnología de próxima generación", maker:"Airbus Helicopters", origin:"Francia", firstFlight:"2015", status:"Activo (certificado 2021)", license:"CPL-H + Type Rating H160", engine:"2 Safran Arrano 1A de 1.100shp c/u", capacity:"2 pilotos + 12 pasajeros", speed:"aprox. 296 km/h", range:"aprox. 850 km", operators:"Bristow (offshore UK), Babcock (SAR Francia), SAMU Francia (HEMS), Japón (JA), varios operadores SAR mundiales", history:"El H160 es el primer helicóptero con rotor Blue Edge (palas curvadas en S) que reduce el ruido en tierra un 50% comparado con generaciones anteriores. Su Fenestron de 11 palas asimétricas es silencioso y seguro en tierra. La certificación costó 9 años de desarrollo. La Armada francesa seleccionó el H160M Guépard como sucesor naval.", interior:"Cabina Helionix digital de última generación, cuatro pantallas táctiles, aviónica sintética 3D." },

  { name:"Leonardo AW189", wiki:"AgustaWestland AW189", group:"Helicópteros", role:"Helicóptero pesado offshore y SAR de largo alcance", maker:"Leonardo (ex-AgustaWestland)", origin:"Italia", firstFlight:"2011", status:"Activo", license:"ATPL helicóptero + Type Rating AW189", engine:"2 General Electric CT7-2E1 de 2.000shp c/u", capacity:"2 pilotos + 16 pasajeros offshore o configuración SAR", speed:"aprox. 296 km/h", range:"aprox. 1.000 km", operators:"Bristow (Mar del Norte), CHC Helicopter, Irish Coast Guard, guardianes costeros de Noruega e Italia, Saudi Aramco, Kuwait", history:"El AW189 es la respuesta de Leonardo al creciente mercado offshore de petróleo y gas en aguas profundas. Su certificación simultánea EASA/FAA en 2014 fue un hito. La versión SAR tiene FLIR, radar de búsqueda y sistema de izado de 272 kg. La Guardia Costera italiana lo opera en el Mar Mediterráneo para rescates de migrantes y náufragos.", interior:"Cabina de 16 plazas offshore con sistema crashworthy certificado, visión nocturna NVG, asientos de absorción de energía." },

  { name:"Mil Mi-38", wiki:"Mil Mi-38", group:"Helicópteros", role:"El helicóptero de transporte mediano más moderno de Rusia", maker:"Mil Moscow Helicopter Plant / Russian Helicopters", origin:"Rusia", firstFlight:"2003", status:"Activo (limitado)", license:"Piloto de helicóptero comercial", engine:"2 Klimov TV7-117V de 2.500shp c/u (versión rusa) o 2 Pratt & Whitney Canada PW127TS", capacity:"2 pilotos + 30 pasajeros o 5.000 kg", speed:"aprox. 320 km/h", range:"aprox. 1.200 km", operators:"Rusia (flota limitada), Bielorrusia", history:"El Mi-38 estaba destinado a reemplazar al Mi-8 en el segmento mediano. El proyecto fue accidentado: empezó con motores occidentales Pratt & Whitney y luego Russia impuso el Klimov TV7 post-sanciones 2014. Alcanzó el récord de altitud para helicópteros de su categoría: 8.600m sobre el nivel del mar. La producción en serie es mínima por costos.", interior:"Cabina presurizada de alta tecnología, sistema de visión nocturna, aviónica digital integrada." },

  { name:"Bell 505 Jet Ranger X", wiki:"Bell 505", group:"Helicópteros", role:"Helicóptero de turbina ligero moderno — el sucesor del JetRanger", maker:"Bell Textron (fabricado en Mirabel, Canadá)", origin:"Canadá / Estados Unidos", firstFlight:"2014", status:"Activo", license:"CPL-H (accesible desde PPL-H)", engine:"1 Safran Arrius 2R de 504shp", capacity:"1 piloto + 4 pasajeros", speed:"aprox. 232 km/h", range:"aprox. 700 km", operators:"Escuelas de vuelo premium, operadores turísticos, fotografia aérea, policía local, agricultura", history:"El Bell 505 es el sucesor directo del legendario Bell 206 JetRanger, el helicóptero ligero de turbina más vendido de la historia. El 505 tiene aviónica Garmin G1000H digital, pantalla táctil y no requiere el mismo tipo rating que el 206. Se usa en escuelas de vuelo de Australia, México, Suiza y China.", interior:"Cabina digital con pantalla Garmin G1000H, vista panorámica de 180°, controles de vuelo modernizados." },

  { name:"Kaman K-MAX", wiki:"Kaman K-MAX", group:"Helicópteros", role:"Helicóptero grúa de rotor intermeshing — el más eficiente para carga aérea", maker:"Kaman Aerospace", origin:"Estados Unidos", firstFlight:"1991", status:"Activo (civil + versión autónoma)", license:"CPL-H tipo especial", engine:"1 Honeywell T53-17A-1 de 1.800shp", capacity:"1 piloto o autónomo, carga máxima 2.722 kg", speed:"aprox. 185 km/h", range:"aprox. 483 km", operators:"Kaman Air, operadores forestales EE.UU., construcción, petróleo y gas, US Marines (versión autónoma)", history:"El K-MAX es el único helicóptero en producción con rotores intermeshing (dos rotores sincronizados que se entrecruzan sin chocarse). Sin rotor de cola, toda la potencia va a sustentación. En Afganistán, los Marines usaron K-MAX autónomos para reabastecimiento sin pilotos — la primera aeronave de carga autónoma en zona de combate real.", interior:"Piloto sienta en silla giratoria que permite verla carga colgante en todo momento." },

  { name:"Airbus H225M Caracal", wiki:"Airbus Helicopters H225M", group:"Helicópteros", role:"Helicóptero de operaciones especiales europeo — CSAR y SOF de largo alcance", maker:"Airbus Helicopters", origin:"Francia", firstFlight:"2000", status:"Activo", license:"Piloto militar avanzado", engine:"2 Turbomeca Makila 2A1 de 1.869shp c/u", capacity:"2 pilotos + 29 soldados o 11 camillas", speed:"aprox. 324 km/h", range:"aprox. 857 km (sin tanques auxiliares)", operators:"Francia (CSAR/SOF), Brasil (Força Aérea), Malasia, México, Tailandia, Kazajistán, Indonesia, Kuwait, Hungría", history:"El H225M Caracal es el helicóptero de operaciones especiales y rescate de pilotos (CSAR) más avanzado de Europa. Francia lo usa para recuperar pilotos derribados en Mali, Libia y Siria. Brasil opera la mayor flota para vigilancia amazónica. Su sonda de reabastecimiento en vuelo permite misiones de más de 1.500 km. La versión civil H225 tuvo un accidente en Noruega 2016 que paralizó la flota offshore.", interior:"Bodega de 17m³, APU de inicio autónomo, FLIR, radar meteorológico, sonda fija de reabastecimiento en vuelo." },

  { name:"Sikorsky SH-3H Sea King (Malvinas)", wiki:"Sikorsky H-3 Sea King", group:"Helicópteros", role:"Helicóptero naval ASW y rescate — el que recogió astronautas del Apollo", maker:"Sikorsky Aircraft", origin:"Estados Unidos", firstFlight:"1959", status:"Activo en algunos países (retirado US Navy)", license:"CPL-H naval o militar", engine:"2 General Electric T58-GE-10 de 1.400shp c/u", capacity:"4 tripulantes + 31 soldados o 4 camillas o equipo ASW", speed:"aprox. 267 km/h", range:"aprox. 1.005 km", operators:"Marina Argentina (ASH-3H desde ARA Hércules), Italia (Agusta-Sikorsky), Japón, Canadá, Alemania, Grecia, India, 30+ países", history:"El Sea King recogió a los astronautas del Apollo 11 tras el amerizaje (1969). La Marina Argentina operó el ASH-3H desde la fragata ARA Hércules en las Malvinas (1982), hundiendo el HMS Sheffield con misiles Exocet — fue el único ataque de misiles lanzados desde helicóptero de la historia del conflicto. Agusta lo fabricó en Italia bajo licencia para decenas de países.", interior:"Anfibio con flotadores laterales, sonar remolcado Bendix AQS-13, torpedos Mk.46 y misiles Exocet AM39." },

];
