import type { Aircraft } from "./types";

export const extraAircraft: Aircraft[] = [
  { name:"Chengdu J-20", wiki:"Chengdu J-20", group:"Militar", role:"Caza furtivo chino", maker:"Chengdu Aerospace", origin:"China", firstFlight:"2011", status:"Activo", license:"Piloto militar avanzado", engine:"WS-10C / WS-15 según evolución", capacity:"1 piloto", speed:"supersónico", range:"largo alcance", operators:"China", history:"Primer caza furtivo chino operativo de quinta generación, clave en la modernización de la PLAAF.", interior:"Cabina digital con aviónica moderna y sensores integrados." },
  { name:"Chengdu J-10", wiki:"Chengdu J-10", group:"Militar", role:"Caza multirrol", maker:"Chengdu Aerospace", origin:"China", firstFlight:"1998", status:"Activo", license:"Piloto militar avanzado", engine:"AL-31FN / WS-10", capacity:"1 piloto", speed:"Mach 2 aprox.", range:"medio alcance", operators:"China, Pakistán", history:"Caza ligero multirrol chino usado para defensa aérea y ataque.", interior:"Cabina monoplaza con aviónica moderna en variantes recientes." },
  { name:"Shenyang J-11", wiki:"Shenyang J-11", group:"Militar", role:"Caza pesado", maker:"Shenyang Aircraft", origin:"China", firstFlight:"1998", status:"Activo", license:"Piloto militar avanzado", engine:"WS-10 / AL-31", capacity:"1 piloto", speed:"Mach 2+", range:"largo alcance", operators:"China", history:"Derivado del Su-27, base de varios desarrollos chinos de caza pesado.", interior:"Cabina de caza pesado con aviónica modernizada según versión." },
  { name:"Shenyang J-15", wiki:"Shenyang J-15", group:"Militar", role:"Caza naval embarcado", maker:"Shenyang Aircraft", origin:"China", firstFlight:"2009", status:"Activo", license:"Piloto naval militar", engine:"WS-10 / AL-31", capacity:"1 piloto", speed:"supersónico", range:"medio/largo alcance", operators:"Armada china", history:"Caza embarcado chino usado en portaaviones, derivado de la familia Su-33.", interior:"Cabina naval preparada para operaciones embarcadas." },
  { name:"Shenyang J-16", wiki:"Shenyang J-16", group:"Militar", role:"Caza de ataque multirrol", maker:"Shenyang Aircraft", origin:"China", firstFlight:"2011", status:"Activo", license:"Piloto militar avanzado", engine:"WS-10", capacity:"2 tripulantes", speed:"supersónico", range:"largo alcance", operators:"China", history:"Caza pesado chino orientado a ataque, interdicción y guerra electrónica en versiones derivadas.", interior:"Cabina biplaza con aviónica de misión." },
  { name:"Xian H-6", wiki:"Xian H-6", group:"Militar", role:"Bombardero estratégico", maker:"Xi'an Aircraft", origin:"China", firstFlight:"1959", status:"Activo", license:"Tripulación militar especializada", engine:"2 turborreactores / turbofán según versión", capacity:"Tripulación militar", speed:"subsónico", range:"largo alcance", operators:"China", history:"Derivado del Tu-16, modernizado para misiones de ataque y lanzamiento de misiles.", interior:"Cabina militar de bombardero con puestos de misión." },
  { name:"Xian Y-20", wiki:"Xian Y-20", group:"Carga", role:"Transporte estratégico", maker:"Xi'an Aircraft", origin:"China", firstFlight:"2013", status:"Activo", license:"Tripulación militar de transporte", engine:"4 turbofán", capacity:"carga militar pesada", speed:"crucero de transporte", range:"largo alcance", operators:"China", history:"Transporte estratégico chino para carga pesada, tropas y logística militar.", interior:"Bodega grande con rampa trasera." },

  { name:"FMA IA-58 Pucará", wiki:"FMA IA-58 Pucará", group:"Militar", role:"Ataque ligero / contrainsurgencia", maker:"Fábrica Militar de Aviones", origin:"Argentina", firstFlight:"1969", status:"Retirado / preservado en varios países", license:"Piloto militar", engine:"2 Turbomeca Astazou", capacity:"2 tripulantes", speed:"aprox. 500 km/h", range:"regional táctico", operators:"Argentina, Uruguay, Colombia, Sri Lanka y otros", history:"Avión argentino de ataque ligero. Participó en la Guerra de Malvinas y en operaciones de contrainsurgencia.", interior:"Cabina biplaza en tándem con visión amplia para ataque cercano." },
  { name:"FMA IA-63 Pampa", wiki:"FMA IA-63 Pampa", group:"Entrenamiento", role:"Entrenador avanzado / ataque ligero", maker:"FAdeA", origin:"Argentina", firstFlight:"1984", status:"Activo", license:"Entrenamiento militar", engine:"Honeywell TFE731", capacity:"2 tripulantes", speed:"subsónico", range:"entrenamiento avanzado", operators:"Argentina", history:"Entrenador avanzado argentino usado por la Fuerza Aérea Argentina.", interior:"Cabina biplaza con aviónica de entrenamiento avanzado." },
  { name:"FMA I.Ae. 27 Pulqui I", wiki:"FMA I.Ae. 27 Pulqui I", group:"Histórica", role:"Primer jet argentino", maker:"Instituto Aerotécnico", origin:"Argentina", firstFlight:"1947", status:"Museo", license:"Piloto de pruebas", engine:"Rolls-Royce Derwent", capacity:"1 piloto", speed:"jet temprano", range:"experimental", operators:"Argentina", history:"Primer avión a reacción diseñado y construido en Latinoamérica.", interior:"Cabina experimental monoplaza de jet temprano." },
  { name:"FMA I.Ae. 33 Pulqui II", wiki:"FMA I.Ae. 33 Pulqui II", group:"Histórica", role:"Caza jet experimental", maker:"Instituto Aerotécnico", origin:"Argentina", firstFlight:"1950", status:"Museo", license:"Piloto de pruebas", engine:"Rolls-Royce Nene", capacity:"1 piloto", speed:"jet subsónico", range:"experimental", operators:"Argentina", history:"Proyecto argentino avanzado de caza a reacción, diseñado con influencia de Kurt Tank.", interior:"Cabina de caza experimental de posguerra." },
  { name:"A-4AR Fightinghawk", wiki:"Lockheed Martin A-4AR Fightinghawk", group:"Militar", role:"Ataque ligero modernizado", maker:"McDonnell Douglas / Lockheed Martin", origin:"Estados Unidos / Argentina", firstFlight:"1954 base A-4", status:"Activo limitado", license:"Piloto militar", engine:"Pratt & Whitney J52", capacity:"1 piloto", speed:"subsónico alto", range:"táctico", operators:"Argentina", history:"Versión modernizada para la Fuerza Aérea Argentina, derivada del A-4M Skyhawk.", interior:"Cabina modernizada con aviónica y radar mejorados." },
  { name:"Dassault Mirage III", wiki:"Dassault Mirage III", group:"Militar", role:"Interceptor supersónico", maker:"Dassault Aviation", origin:"Francia", firstFlight:"1956", status:"Retirado en muchos países", license:"Piloto militar avanzado", engine:"SNECMA Atar", capacity:"1 piloto", speed:"Mach 2", range:"interceptor", operators:"Francia, Argentina, Israel, Suiza, Australia y otros", history:"Caza delta emblemático de la Guerra Fría; usado por Argentina y muchos países.", interior:"Cabina de interceptor clásico supersónico." },
  { name:"Dassault Super Étendard", wiki:"Dassault-Breguet Super Étendard", group:"Militar", role:"Ataque naval", maker:"Dassault-Breguet", origin:"Francia", firstFlight:"1974", status:"Retirado / preservado", license:"Piloto naval militar", engine:"SNECMA Atar 8K-50", capacity:"1 piloto", speed:"subsónico alto", range:"ataque naval", operators:"Francia, Argentina, Irak", history:"Conocido por su empleo naval y por la Guerra de Malvinas con misiles Exocet.", interior:"Cabina monoplaza naval de ataque." },

  { name:"Sukhoi Su-27", wiki:"Sukhoi Su-27", group:"Militar", role:"Caza de superioridad aérea", maker:"Sukhoi", origin:"Rusia / URSS", firstFlight:"1977", status:"Activo", license:"Piloto militar avanzado", engine:"2 Saturn AL-31", capacity:"1 piloto", speed:"Mach 2+", range:"largo alcance", operators:"Rusia, China, Ucrania y otros", history:"Caza pesado soviético diseñado para enfrentar cazas occidentales de cuarta generación.", interior:"Cabina de caza pesado con instrumentación militar." },
  { name:"Sukhoi Su-30", wiki:"Sukhoi Su-30", group:"Militar", role:"Caza multirrol pesado", maker:"Sukhoi", origin:"Rusia", firstFlight:"1989", status:"Activo", license:"Piloto militar avanzado", engine:"2 AL-31", capacity:"2 tripulantes", speed:"Mach 2", range:"largo alcance", operators:"Rusia, India, China, Argelia, Venezuela y otros", history:"Exportado ampliamente como caza multirrol pesado.", interior:"Cabina biplaza para piloto y operador de sistemas." },
  { name:"Sukhoi Su-35", wiki:"Sukhoi Su-35", group:"Militar", role:"Caza multirrol avanzado", maker:"Sukhoi", origin:"Rusia", firstFlight:"2008", status:"Activo", license:"Piloto militar avanzado", engine:"2 Saturn AL-41F1S", capacity:"1 piloto", speed:"Mach 2+", range:"largo alcance", operators:"Rusia, China, Egipto y otros", history:"Evolución avanzada de la familia Su-27 con supermaniobrabilidad y aviónica moderna.", interior:"Cabina digital moderna." },
  { name:"Mikoyan MiG-21", wiki:"Mikoyan-Gurevich MiG-21", group:"Histórica", role:"Interceptor supersónico", maker:"Mikoyan-Gurevich", origin:"URSS", firstFlight:"1955", status:"Activo residual / histórico", license:"Piloto militar", engine:"Tumansky R-25 y variantes", capacity:"1 piloto", speed:"Mach 2", range:"interceptor", operators:"Más de 50 países", history:"Uno de los cazas supersónicos más producidos y exportados de la historia.", interior:"Cabina compacta de interceptor de Guerra Fría." },
  { name:"Ilyushin Il-76", wiki:"Ilyushin Il-76", group:"Carga", role:"Transporte pesado", maker:"Ilyushin", origin:"URSS / Rusia", firstFlight:"1971", status:"Activo", license:"Tripulación especializada", engine:"4 Soloviev D-30 / PS-90", capacity:"carga militar pesada", speed:"aprox. 850 km/h", range:"largo alcance", operators:"Rusia, India, China y numerosos países", history:"Transporte estratégico soviético/ruso muy usado en logística militar y humanitaria.", interior:"Bodega amplia con rampa trasera." },

  { name:"HAL Tejas", wiki:"HAL Tejas", group:"Militar", role:"Caza ligero multirrol", maker:"HAL", origin:"India", firstFlight:"2001", status:"Activo", license:"Piloto militar avanzado", engine:"General Electric F404", capacity:"1 piloto", speed:"supersónico", range:"táctico", operators:"India", history:"Caza ligero indio desarrollado para reemplazar aviones antiguos y fortalecer industria local.", interior:"Cabina digital moderna." },
  { name:"KAI T-50 Golden Eagle", wiki:"KAI T-50 Golden Eagle", group:"Entrenamiento", role:"Entrenador avanzado / ataque ligero", maker:"KAI / Lockheed Martin", origin:"Corea del Sur", firstFlight:"2002", status:"Activo", license:"Entrenamiento militar", engine:"General Electric F404", capacity:"2 tripulantes", speed:"supersónico", range:"entrenamiento avanzado", operators:"Corea del Sur, Indonesia, Irak, Filipinas, Tailandia y otros", history:"Entrenador supersónico surcoreano con variantes de ataque ligero.", interior:"Cabina biplaza moderna." },
  { name:"KAI KF-21 Boramae", wiki:"KAI KF-21 Boramae", group:"Militar", role:"Caza avanzado", maker:"KAI", origin:"Corea del Sur", firstFlight:"2022", status:"En desarrollo / pruebas", license:"Piloto militar avanzado", engine:"2 General Electric F414", capacity:"1 piloto", speed:"supersónico", range:"medio/largo alcance", operators:"Corea del Sur", history:"Programa surcoreano de caza avanzado para fortalecer independencia tecnológica.", interior:"Cabina digital de nueva generación." },
  { name:"Mitsubishi F-2", wiki:"Mitsubishi F-2", group:"Militar", role:"Caza multirrol", maker:"Mitsubishi / Lockheed Martin", origin:"Japón", firstFlight:"1995", status:"Activo", license:"Piloto militar avanzado", engine:"General Electric F110", capacity:"1 o 2 tripulantes", speed:"supersónico", range:"táctico", operators:"Japón", history:"Desarrollo japonés basado en el F-16, adaptado a necesidades nacionales.", interior:"Cabina moderna con aviónica japonesa." },
  { name:"Mitsubishi A6M Zero", wiki:"Mitsubishi A6M Zero", group:"Histórica", role:"Caza embarcado WWII", maker:"Mitsubishi", origin:"Japón", firstFlight:"1939", status:"Histórico", license:"Licencia histórica", engine:"Nakajima Sakae", capacity:"1 piloto", speed:"aprox. 533 km/h", range:"largo alcance para su época", operators:"Japón", history:"Caza naval japonés emblemático de la Segunda Guerra Mundial.", interior:"Cabina de caza naval clásico." },

  { name:"Comac C919", wiki:"Comac C919", group:"Comercial", role:"Narrow-body", maker:"COMAC", origin:"China", firstFlight:"2017", status:"Activo", license:"ATPL + habilitación", engine:"CFM LEAP-1C", capacity:"158-192 pasajeros aprox.", speed:"crucero comercial", range:"medio alcance", operators:"China Eastern y operadores chinos", history:"Avión comercial chino diseñado para competir en el segmento A320/737.", interior:"Cabina de pasillo único moderna." },
  { name:"Embraer C-390 Millennium", wiki:"Embraer C-390 Millennium", group:"Carga", role:"Transporte militar táctico", maker:"Embraer", origin:"Brasil", firstFlight:"2015", status:"Activo", license:"Tripulación militar", engine:"2 IAE V2500", capacity:"carga militar / tropas", speed:"jet táctico", range:"medio/largo alcance", operators:"Brasil, Portugal, Hungría y otros", history:"Transporte militar brasileño moderno y exportable.", interior:"Bodega de carga con rampa trasera." }
];
